plugins/Tools/RotateTool/RotateTool.py

Fixes a problem where rotation would not snap to the right angles, and was therefore not terribly useful

in RotateTool, make angle a multiple of _snap_angle when _snap_rotation is enabled

---

UM/Qt/QtApplication.py

Use slice to get the only major and minor version.

Fix: when PYQT_VERSION_STR does not contain patch, the unpack will fail.

---

UM/Scene/Platform.py

https://github.com/Ultimaker/Uranium/commit/78ee44b2c5c00628de4a16b90ea87000272fa076 was a quick fix for when no mesh filename is set by supplying an empty filename. https://github.com/Ultimaker/Uranium/commit/e20745af40d78591239a176721d6d3b53aee7b80 changed how MeshReading returns when the read operation fails. Because of this the quick fix doesn't work anymore. This PR is an updated fix for the problem.

Better fix for crash when no platform mesh is set

---

UM/Qt/Bindings/MainWindow.py

Currently Uranium only stores the window size. When the window is maximized, the size is also stored as is. This makes the "restore size" function of the window useless (because both the maximized and restored window size are the same). Also on Windows the window is actually a couple of pixels wider than fullscreen because the window has a border.
This PR only stores the window-size when the window is not maximized. Additionally it stores the window position and the window state.
The PR contains a workaround for a Qt bug in Windows, where the windowState is not updated until after the moveEvent and resizeEvent have fired:
https://bugreports.qt.io/browse/QTBUG-30085

Store window position and maximized state

---

plugins/Tools/TranslateTool/TranslateTool.py

The translate tool moves objects with an offset on subsequent operations.
Steps to reproduce before fix:
* Load object
* Use translate tool to move object around (either one of the axes, or the object itself)
-> behaves as expected
* Use translate tool again
-> jumps to an offset position, moves correctly with object

Fix translate tool moving objects with an offset

---

UM/Settings/MachineManager.py

Steps to reproduce:
* delete cura profile
* start cura
=> machine wizard pops up
* close machine wizard
=> no machine is added
* close cura
=> crash because _active_machine is None

Fix crash on exit when no machine is selected

---

UM/Qt/Bindings/MainWindow.py

If the window is positioned on an secondary screen when Cura is closed, and Cura is subsequently opened without the secondary screen being available, the window is drawn fully off-screen. This PR checks if (part of) the window is on the currently available screen(s), and moves the window back to the primary screen.

Make sure window is not positioned off-screen

---

UM/Qt/qml/UM/Settings/SettingView.qml

The advanced settings pane can be dragged horizontally, which is weird.
Steps to reproduce:
* Switch to advanced settings
* Expand a couple of categories
* Drag the scrollview horizontally
Expected result:
Dragging horizontally has doesn't

Disable dragging the advanced settings pane horizontally

---

UM/Operations/LayFlatOperation.py
UM/Qt/qml/UM/MessageStack.qml
UM/Scene/Selection.py
plugins/Tools/RotateTool/RotateTool.py
plugins/Tools/RotateTool/RotateTool.qml

Reissue of #79, against 2.1 branch
Mostly a straight port of @daid's version in legacy cura:
https://github.com/daid/Cura/blob/SteamEngine/Cura/util/printableObject.py#L207
Changes:
* Swap Y & Z axes
* Add progressbar during calculation
* (Add button to rotatetool panel)
* Iterate over all selected objects

Add "Lay flat" functionality

---

CMakeLists.txt

Instead of having a list of languages hardcoded, we scan the i18n directory for available languages.
It was a TODO, which was left after fixing po-file installation. The reference to the added macro is there as an URL.
This has been already applied to Cura, but same is needed here (commit e1966a7ea59933f72e1a8fdf35ae06398c626f4b)

Scanning i18n directory for languages

---

UM/Controller.py
UM/Qt/Bindings/ControllerProxy.py
plugins/Tools/MirrorTool/MirrorTool.py
plugins/Tools/RotateTool/RotateTool.py
plugins/Tools/ScaleTool/ScaleTool.py
plugins/Tools/SelectionTool/SelectionTool.py
plugins/Tools/TranslateTool/TranslateTool.py

This patch disables tools while a tooloperation is running. Some tool-operations, such as the Lay Flat operation, take a while to complete. It should not be possible to relaunch the lay flat operation while the same operation is already loading. Also manipulating an object with a different tool while an operation is running may affect the outcome of either tools.
Fixes CURA-623
Also see https://github.com/Ultimaker/Cura/pull/606

Prevent starting a new tooloperation while a tooloperation is running

---

UM/Qt/Bindings/ActiveProfileProxy.py
UM/Qt/Bindings/ActiveToolProxy.py
UM/Qt/Bindings/ContainerProxy.py
plugins/Tools/RotateTool/RotateTool.qml
plugins/Tools/ScaleTool/ScaleTool.qml

This is a way to handle Python containers in QML without the performance penalties of constantly converting to QVariantMap/QVariantList.

Introduce UM.Qt.Bindings.ContainerProxy class

---

UM/Qt/Bindings/ActiveProfileProxy.py
UM/Qt/Bindings/Bindings.py
UM/Qt/Bindings/MachineInstancesModel.py
UM/Qt/Bindings/MachineManagerProxy.py
UM/Qt/Bindings/MachineMaterialsModel.py
UM/Qt/Bindings/ProfilesModel.py
UM/Qt/Bindings/SettingCategoriesModel.py
UM/Qt/Bindings/SettingsFromCategoryModel.py
UM/Qt/qml/UM/Dialog.qml
UM/Qt/qml/UM/Preferences/ManagementPage.qml
UM/Qt/qml/UM/Preferences/PreferencesDialog.qml
UM/Qt/qml/UM/Preferences/ProfilesPage.qml
UM/Qt/qml/UM/Preferences/RenameDialog.qml
UM/Qt/qml/UM/Preferences/SettingVisibilityPage.qml
UM/Qt/qml/UM/Settings/SettingView.qml
UM/Qt/qml/UM/Settings/SidebarCategoryHeader.qml
UM/Resources.py
UM/Settings/MachineDefinition.py
UM/Settings/MachineInstance.py
UM/Settings/MachineManager.py
UM/Settings/Profile.py
UM/Settings/Setting.py
UM/Settings/SettingOverrideDecorator.py
UM/Settings/SettingsCategory.py

This is a reimagining of how profiles work in Cura. Instead of automatically creating new profiles when the user tries to change a setting on a "readonly" profile and having multiple changed profiles, there is only one "working profile" per machine type. This is more akin to how Legacy Cura worked.
This PR also implements different profiles for different printer types, variants (nozzle sizes in the UI) and materials. Finally it contains numerous little UX improvements related to profiles.
Also see Cura PR: https://github.com/Ultimaker/Cura/pull/618
Fixes or contributes to:
CURA-547
CURA-430 (hopefully)
CURA-805
CURA-199
CURA-402
CURA-583
CURA-626
CURA-24
CURA-751
CURA-569
CURA-568
CURA-432

Profiles rework

---

UM/Qt/Bindings/MachineManagerProxy.py
UM/Settings/MachineDefinition.py
UM/Settings/MachineManager.py

Adds a "Select Upgraded Parts" wizard page when adding an UM2 or UM2 Extended, allowing the user to select the Olsson block upgrade.
The change in Uranium is necessary to switch the machine definition of an existing machine instance to switch it from "ultimaker2" to "ultimaker2_olsson" in the wizard.
Also see https://github.com/Ultimaker/Cura/pull/636
Fixes CURA-91

Support UM2 with Olsson block upgrade

---

UM/Qt/GL/QtOpenGL.py

When executing glGetString(self._gl.GL_VENDOR) it returns here on Ubuntu Xenial (armhf) using closed-source mali drivers "None".
Therefore .lower() fails. I think for now replacing the None-Type with "" is ok for now.
* Related to https://github.com/Ultimaker/Uranium/pull/116

GLESv2: Make GL_VENDOR check more failsave

---

UM/Mesh/MeshData.py

It seems that some CAD applications export the number of faces as floating point numbers. Our STL loader seems not to care about this and passes num_faces as float().
This commit converts the floating point value into int() as needed. Of course, we should check about this much earlier.
This might be useful to backport to a bugfix version of 2.1.

[master] Mesh: Converting floating point faces into int()

---

UM/Logger.py

This will add logger outputs like:
```
2016-03-18 15:51:06,332 - INFO - <PATH>/UM/PluginRegistry.py (loadPlugin [61]): Loaded plugin ChangeLogPlugin
2016-03-18 15:51:06,334 - INFO - <PATH>/UM/Qt/QtApplication.py (__init__ [36]): Command line arguments: {'file': [], 'disable-textures': False, 'external-backend': False, 'debug-mode': False}
2016-03-18 15:51:06,481 - WARNING - <PATH>/UM/Settings/MachineManager.py (saveVisibility [707]): No active machine found when trying to save setting visibility
2016-03-18 15:51:06,588 - WARNING - <PATH>/UM/Settings/Profile.py (setSettingValue [148]): Tried to set value of non-user setting platform_adhesion
2016-03-18 15:51:06,590 - WARNING - <PATH>/UM/Settings/Profile.py (setSettingValue [148]): Tried to set value of non-user setting platform_adhesion …
```

[master] tracing for logger

---

plugins/ConsoleLogger/ConsoleLogger.py

In case the colorlog module is installed, it's Formatter will be used to colorize the output.
It improves the possibility to find ERRORs and WARNINGs.
It should be no problem to make that available on Windows and OSX, too, as colorlog is crossplatform and handles the different ways to pass the colors to the terminals.

[master] ConsoleLogger: Optional colored output

---

UM/Mesh/ReadMeshJob.py

When objects have been modeled with meters as units, they become so tiny that the cannot be selected in Cura to be scaled up.
See https://github.com/Ultimaker/Cura/issues/697#issuecomment-209518061
Also see https://github.com/Ultimaker/Cura/pull/733

Optionally scale meshes that are so tiny they could not otherwise be selected

---

UM/Application.py

For example, if the community distributes Cura in a different way, they
can set CURA_BUILDTYPE via 'cmake -DCURA_BUILDTYPE=' and whenever Cura
is launched " (PPA)" will be appended. Of course, this could be done by
appending " (PPA)" to CURA_VERSION, but in case of my Ubuntu/Debian
packaging it will only need one modification in debian/changelog to
change the version. During build (debian/rules) this version will be
read from debian/changelog.
Changing the version number across different files, is a waste of time.
Finally, we can use that field in the future to indicate debug or other
other special builds.
* Needed by: https://github.com/Ultimaker/Cura/pull/764

[master] Adding a field of the build type to the spashscreen.

---

CMakeLists.txt

This is needed here to pass the test suite. When it compares strings it compares untranslated with translated and therefore fails.
```
thopiekar@home:~/Projekte/eclipse-Ultimaker/Uranium/build$ make tests
========================================================= test session starts =========================================================
platform linux -- Python 3.5.1+, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /home/thopiekar/Projekte/eclipse-Ultimaker/Uranium, inifile: pytest.ini
collected 247 items 
../tests/TestDecorators.py .
../tests/TestSignals.py ..
../tests/Jobs/TestJobQueue.py .......
../tests/Math/TestAxisAlignedBox.py .....
../tests/Math/TestMatrix.py ..........
../tests/Math/TestPlane.py ..
../tests/Math/TestPolygon.py ................
../tests/Math/TestQuaternion.py …
```

[master] Tests: Switch to default language

---

UM/Resources.py
UM/Settings/ContainerRegistry.py
UM/Settings/DefinitionContainer.py

This contains two major changes:
* Sort the list of files to load by the container type. This ensures we load DefinitionContainers before InstanceContainers and InstanceContainers before ContainerStacks.
* Use pickle to cache a binary version of the DefinitionContainer that is much faster to load. This reduces startup time on my machine from ~5 seconds to ~3 seconds.

Improvements to ContainerRegistry::load

---

UM/Qt/qml/UM/Preferences/SettingVisibilityPage.qml
UM/Settings/Models/SettingDefinitionsModel.py
UM/Settings/Models/SettingPreferenceVisibilityHandler.py
UM/Settings/Models/SettingVisibilityHandler.py
UM/Settings/SettingDefinition.py

This is a reimplementation of SettingDefinitionsModel that is both simpler and faster. It is designed to never trigger a complete model reset apart from containerId or root property changes. In addition, it fixes a number of bugs currently present in the model:
* Children-of-children are visible even if their parents are not
* Empty categories are hidden
* Filtering removes rows instead of hiding the data
* Allow setting the expanded settings so we can re-enable saving and loading of expanded categories.
* Row changes are done through insertRows/removeRows which prevents a complete model reset and only changes things that actually changed.
Additionally this paves the way for creating an "EnabledVisibilityHandler" that modifies visibility based on the enabled property.

New SettingDefinitionsModel

---

UM/Qt/Duration.py

Currently we are not passing the print duration in ISO format.
This will make it possible to get it directly from our print_information variable in SliceInfo plugin.

CURA-1445: Adding getDurationInISOFormat

---

UM/Logger.py

* Don't format lines from traceback
* Directly pass args to self.log()
* Format message only once
* Only format messages when args are passed
Contributes to CURA-1445 and CURA-1771

Logger: fixes for logException

---

UM/Math/Color.py

RGB-colors are commonly represented as "web-friendly" #RRGGBB strings (eg #ffffff for white). This PR adds convenience functions to the UM.Math.Color class to convert to/from this format. Usefull in cases where colors are specified in configurations.

Convenience functions to convert a UM.Math.Color to/from a hex-string

---

UM/Qt/Bindings/DirectoryListModel.py
UM/Qt/Bindings/MeshListModel.py
UM/Qt/Bindings/PluginsModel.py
UM/Qt/Bindings/ToolModel.py
UM/Qt/Bindings/ViewModel.py
UM/Qt/ListModel.py
UM/Settings/Models/ContainerStacksModel.py
UM/Settings/Models/DefinitionContainersModel.py
UM/Settings/Models/InstanceContainersModel.py

setItems sets the items to a (presorted) list of items instead of adding items one by one and then sorting the list. This way if an update to the model causes a signal storm at least it happens only once for an update.
Fixes CURA-1838, contributes to CURA-2193

Add ListModel.setItems

---

UM/Settings/ContainerRegistry.py
UM/Util.py

Only use regular expressions when we need to. Most of the time simple string comparison is all that is needed.
This cuts the loading time of Cura by ~35% for me (from 43 to 34 seconds on my machine). Specifically, and in combination with the optimisation in https://github.com/Ultimaker/Cura/commit/30a679ddf9019aad721e8b1deccd7e453a216683 this has cut deserialisation of the XMLMaterialProfiles from 24 seconds to 4 seconds.
I am putting this in a PR because I am not 100% sure it does not break things; it needs testing, and I am curious to know if it speeds things up on other systems as dramatically as it does on mine.
CURA-2187

Massively speedup ContainerRegistry.findContainers()

---

UM/Resources.py

While embedding fdm_materials inside I had problems because UM.Resources
tried in another function to guess the MIME type of .git/index. So I
decided to make UM.Resources ignore all "dot directories", which are
hidden on Linux, but visible on Windows.
I added a print(root) between line 88 and 89 to be sure only the .git
directory is ignored here and this is the result:
```
C:\Users\thopi\Documents\GitHub\Cura\resources\materials\.git
C:\Users\thopi\Documents\GitHub\Cura\resources\materials\.git\hooks
C:\Users\thopi\Documents\GitHub\Cura\resources\materials\.git\info
C:\Users\thopi\Documents\GitHub\Cura\resources\materials\.git\logs
C:\Users\thopi\Documents\GitHub\Cura\resources\materials\.git\logs\refs
C:\Users\thopi\Documents\GitHub\Cura\resources\materials\.git\logs\refs\heads …
```

Resources: Ignore dot directories inside resources

---

UM/Resources.py

Change config storage path to use back-slashes on Windows
Python magically fixes mixed slashes and backslashes in paths on Windows. However the storage path gets compared to the full path of files when loading configs to determine readonly state, and this comparison fails if the config storage path uses forward-slashes. The result is that all config files are treated as readonly, including quality_changes and user profiles. This is only really visible in the Profiles preference pane; after restarting Cura all profiles are shown as protected profiles.
Note that this only seems to be necessary in master; I have not yet found out when the readonly state broke in master compared to 2.3.

Fix readonly state of profiles on Windows

---

UM/Settings/ContainerStack.py
UM/Settings/Models/SettingPropertyProvider.py

This contains two changes: Replacing the dict in SettingPropertyProvider with QQmlPropertyMap, which is a dict-like object that allows QML bindings on individual keys in the dictionary so we do not constantly need to update the entire dict when a single property changes.
The other change is to collect all property change signals that should be handled by ContainerStack and emit them together. This reduces the amount of duplicate signals emitted by ContainerStack and allows us to emit a single signal that references all properties that have changed.
These changes combined reduce the time needed to handle toggling "Enable Support" from 140ms down to 40ms, according to the QML profiler.

Improve Performance of SettingPropertyProvider and property changes

---

UM/Qt/Bindings/Theme.py

A fixed width font is useful for displaying code, eg start/end-gcode in Cura.

Add a system-defined monospaced font to the theme

---

UM/Settings/ContainerStack.py

This PR adds an optional parameter to ContainerStack.addContainer that makes it possible to add a container at the specified index in an existing stack, instead of always at the top. If the parameter is not specified, the container is added to the top of the stack as before the PR.

Allow adding a container at a specified index in the stack

---

CMakeLists.txt

As discussed on JIRA the best way to add our environment variables is to pass them via "set_tests_properties". Of course, this depends on #171, which begins to use the set of commands provided by CMake to declare tests.
However, there seems to be a problem in the test suite, therefore it isn't working  completely now.
Fixes: #171 
(Includes: #171 )
Contributes to CURA-1697
Contributes to CURA-1764

CURA-1764: Appending environment variables with set_tests_properties

---

plugins/UpdateChecker/UpdateChecker.py

As you can see from the diff the work on this plugin was not finished.
Moved the needed function into the job and added a message for the case
someone makes the job non-silent. The developer might think at the
moment, when seeing that the message appears: "No new version was
found." .. that everything is fine.
So to make it clear I added a message which is sent to the UIX.
Contributes to CURA-2970

UpdateChecker: Completing work and additions

---

UM/Settings/Models/InstanceContainersModel.py

This PR adds a "All Supported Types" filter to the import profile dialog as the default option. This way the functionality to import gcode and legacy profiles are no longer hidden from the user; as it is now the user must manually switch filetypes to even see gcode or legacy profiles. Especially on OSX this is quite hidden.

Add "All Supported Types" option to profile import dialog

---

UM/Logger.py

This PR changes logging to log the full classpath of the class that wants to print the logging, rather than using the file name. This avoids printing filenames of build systems and fixes logging when using the AppImage or other tools that modify paths.
In addition, this adds support for using str.format() for logging messages.

Fix logging filenames

---

UM/Settings/ContainerStack.py
tests/Settings/TestContainerStack.py

This changes how the containers stored in a ContainerStack are serialized, from a single entry with a comma-separated list to a single section with index, container_id entries. This simplifies the code and allows ConfigParser to deal with special characters and parsing. A bonus is that the resulting config file is easier to read.
The old format is still supported when deserializing to make sure this is properly backward compatible. In addition, I updated the unit tests and created two additional tests, on for backward compatibility and one for special characters.
Contributes to issue CURA-3098.

Change ContainerStack serialization format to handle special characters properly

---

plugins/Tools/CameraTool/CameraTool.py

1. Zoom in bug.
When you continue zoom in after you don't see visual difference, then you must zoom out same amount after you will see visual zoom out.
In CameraTool.py "self._min_zoom = 0" but mathematically it will move endlessly closer to 0.
"self._min_zoom = 1" is fixing that bug
2. space + mouse zoom jump
Space + mouse zoom "jump"(zoom in or out) sometimes when start new zoom. ( only with "space + mouse" zoom)
Script don't reset sometimes "self._start_y" value before next zoom.
added reset when "space" is not active.
Maybe not best option but it will fix that bug

Camera control bugs

---

UM/Qt/GL/QtTexture.py

QImage() returns an image with uninitialised data. This could cause the buildplate of machines that don't have a texture (EG UMO) to become a random color.

Fix build plate color for printers without a build plate texture

---

UM/Qt/GL/QtOpenGL.py

Based on @heinervdm's fix:
https://github.com/Ultimaker/Cura/issues/1117#issuecomment-259081608
Fixes: https://github.com/Ultimaker/Cura/issues/1117
Fixes: https://github.com/thopiekar/Cura-packaging/issues/12

CURA-3191: QtOpenGL: Adding workaround for undecodable string

---

UM/Qt/GL/QtOpenGL.py

Based on @heinervdm's fix:
https://github.com/Ultimaker/Cura/issues/1117#issuecomment-259081608
Fixes: https://github.com/Ultimaker/Cura/issues/1117
Fixes: https://github.com/thopiekar/Cura-packaging/issues/12

QtOpenGL: Adding workaround for undecodable string

---

UM/Qt/Bindings/Theme.py
UM/Qt/QtApplication.py
UM/Scene/ToolHandle.py
UM/View/CompositePass.py
UM/View/SelectionPass.py
plugins/Tools/MirrorTool/MirrorTool.py
plugins/Tools/MirrorTool/MirrorToolHandle.py
plugins/Tools/RotateTool/RotateTool.py
plugins/Tools/RotateTool/RotateToolHandle.py
plugins/Tools/ScaleTool/ScaleTool.py
plugins/Tools/ScaleTool/ScaleTool.qml
plugins/Tools/ScaleTool/ScaleToolHandle.py
plugins/Tools/TranslateTool/TranslateTool.qml
plugins/Tools/TranslateTool/TranslateToolHandle.py

This PR makes the Theme layer available to python, so it can be used to theme the parts of the UI that is governed by python as opposed to QML, most notably the viewport. This paves the road for a dark theme, among other things.
Note that the theme relies on the qml engine to exist; the theme should not be accessed before Application.engineCreatedSignal is fired.
This PR relies on its Cura counterpart: https://github.com/Ultimaker/Cura/pull/1370

Themeable viewport

---

UM/VersionUpgradeManager.py

This PR checks we got a valid result from upgrade_step() before trying to split the result so we get the intended warning instead of a (double printed?) exception.

Fix exception when file cannot be upgraded

---

UM/Scene/ToolHandle.py
UM/View/SelectionPass.py
plugins/Tools/MirrorTool/MirrorToolHandle.py
plugins/Tools/RotateTool/RotateToolHandle.py
plugins/Tools/ScaleTool/ScaleToolHandle.py
plugins/Tools/TranslateTool/TranslateToolHandle.py

When the colors for toolhandles are themed, we cannot rely on these colors being unique between axes, or between potential other "special" colors in the selection pass. This PR restores fixed constant colors per axis, for the selection meshes only. These fixed colors are never visible to the user because they are only used in the selection pass.
This PR is a followup for https://github.com/Ultimaker/Uranium/pull/215

Fix toolhandle selection colors

---

UM/Settings/ContainerQuery.py
UM/Settings/ContainerRegistry.py
UM/Signal.py
tests/benchmarks/Settings/BenchmarkContainerRegistry.py

This reduces the time it takes to switch variant on an UM3 from ~14 seconds on my machine to ~1.6 seconds.
It introduces two changes: 
* A way to postpone signals so they are emitted later, with optional compression (making sure to only emit a signals once).
* A cache for queries in ContainerRegistry::findContainers.
We make a lot of calls to findContainers, often without any of the underlying list of containers changing. By caching the result, we can improve those cases, since we do not need to execute the expensive search operation again.
This fixes CURA-3312

Improve performance of switching variant/materials/quality

---

plugins/Tools/CameraTool/CameraTool.py

CameraTool disables cursorkey control of the camera when the Ctrl modifier is pressed, but not when both the Ctrl and (eg) Shift modifier is pressed.
This enables eg stepping through layers in Cura faster (Ctrl + Shift + Up/Down) without affecting the camera.

Disable camera control with cursor keys when >1 modifiers are pressed

---

UM/Settings/Models/ContainerPropertyProvider.py

Fixes this issue:
```
Version: 2.4.99-master.20170309034509
Platform: Windows-10-10.0.14393
Qt: 5.7.1
PyQt: 5.7.1
Exception:
Traceback (most recent call last):
File "D:/master/build/inst/lib/python3.5/site-packages/UM\Settings\Models\ContainerPropertyProvider.py", line 75, in setKey
File "D:/master/build/inst/lib/python3.5/site-packages/UM\Settings\Models\ContainerPropertyProvider.py", line 135, in _update
File "D:/master/build/inst/lib/python3.5/site-packages/UM\Settings\Models\ContainerPropertyProvider.py", line 142, in _getPropertyValue
File "D:/master/build/inst/lib/python3.5/site-packages/UM\Settings\InstanceContainer.py", line 214, in getProperty
File "D:/master/build/inst/lib/python3.5/site-packages/UM\Settings\InstanceContainer.py", line 398, in _instantiateCachedValues
File …
```

CURA-3482 Handle the case where a property doesn't exist

---

plugins/Tools/CameraTool/CameraTool.py

Adds a way to invert the zoom direction for Cura. A few engineers requested this, as it matches the default solid works behavior better. Also see https://github.com/Ultimaker/Cura/pull/1548

Added invert zoom preference option

---

UM/FileHandler/FileReader.py

`preRead()` in `ThreeMFWorkspaceReader` shows a summary dialog. We want to use `preRead()` for checking whether a file is a valid project file, so in this case, the dialog is not desired.
We change the base `preRead()` to take a flexible number of arguments, so we can pass something like a `show_dialog=True/False` argument to `ThreeMFWorkspaceReader.preRead()`.

CURA-3495 Allow preRead() to take flexible arguments

---

UM/Qt/qml/UM/Dialog.qml

The calculation of screenScaleFactor (QtApplication.py) is fairly naive and has an arbitrary cutoff. It fails on my new 1080p 13" laptop (which has a ~160 DPI resolution): dialog windows (which don't set their own sizes) become a factor 2 too large.
It also does not take into account future screens that might have a higher screen scale factor (new iPads already have a scale factor of 3, so it is not unlikely that we will get 3x screens in computers).
Screen.devicePixelRatio works everywhere else in Cura and Uranium, so I don't know why this screenScaleFactor was introduced in the first place. Perhaps the analysis of CURA-422 has an answer, but I don't have access to that anymore.

Fix size of dialogs on high-ish DPI screens

---

UM/Resources.py

~/AppData/Local may not be correctly expanded to the AppData folder on systems with itinerant profiles (eg corporate/educational networks where the user profile is stored on the network)
See https://github.com/Ultimaker/Cura/issues/1369 for discussion
Also see the Cura PR: https://github.com/Ultimaker/Cura/pull/1375

Fix the location of the configuration folder on Windows

---

UM/Resources.py

Applications should use the Roaming AppData folder for data that is supposed to follow the user around on different computers.
Followup to https://github.com/Ultimaker/Uranium/pull/216
See https://github.com/Ultimaker/Cura/issues/1369 for discussion
This changes the path for configurations, so an upgrade step needs to be implemeted. Now is a good time to make this change, since the configuration folder structure is changing anyway: https://github.com/Ultimaker/Uranium/pull/234

Use Roaming instead of Local AppData on Windows

---

UM/Settings/ContainerRegistry.py

This PR prevents loading containers from "old/" folders. These files are backups from the version upgrade system. 
This fixes https://github.com/Ultimaker/Cura/issues/1902, https://github.com/Ultimaker/Cura/issues/1855, https://github.com/Ultimaker/Cura/issues/1874 and many others in the forum
See https://github.com/Ultimaker/Cura/issues/1902#issuecomment-305257112

Prevent loading containers from "old" folders

---

UM/Math/Polygon.py

This change is a no-op when using the original scipy.spatial.ConvexHull, as that implementation will return the original array in hull_result.points.
However, this change makes the code more robust and will make it operate correctly even if the underlying library returns a changed points array. I ran into this issue when creating my own version of "scipy.spatial.ConvexHull" that used a different underlying algorithm.

Make hull using points returned from ConvexHull

---

UM/Application.py
UM/Qt/Bindings/Theme.py
UM/Resources.py

This PR implements simple theme inheritance. Themes no longer have to be complete; they can simply inherit a default theme.
A very minimal theme that only changes the background of the sidebar to read could be as simple as this theme.json file:
```
{
"metadata": {
"name": "Red Sidebar",
"inherits": "cura"
},
"colors": {
"sidebar": [255, 0, 0, 255]
}
}
```
In addition to this inheritance, the PR also adds a small function to list all themes in the relevant resource locations (ie: both in the application folder and in the configuration folder). For this to be useful, a small change in Cura is required. See the separate Cura PR: https://github.com/Ultimaker/Cura/pull/1878

Theme inheritance

---

UM/Qt/Bindings/PointingRectangle.py

This PR implements a true border for UM.PointingRectangle. Since I introduced the PointingRectangle it has always irked me that I needed to add two PointingRectangles to draw one with a border, and hope the second one always nicely aligns with the first one. Now a PointingRectangle can draw its own border, like it should.

PointingRectangle border

---

UM/Settings/Models/SettingDefinitionsModel.py

This PR prevents showing empty category headers in the sidebar.  SettingDefinitionModel:_isAnyDescendantVisible() only checked if there are settings that are marked to be "visible" (in the Settings Visibility page), but not if they are "enabled" for the current machine. 
eg: "Enable Prime Tower" is a setting that is made visible by default, but it is disabled (hidden) with "enabled": "machine_extruder_count > 1". So you get an empty category for all single extrusion printers.
This PR fixes https://github.com/Ultimaker/Cura/issues/2126
The performance impact of this change should be checked.

Hide empty categories

---

UM/Qt/qml/UM/Preferences/MachinesPage.qml
UM/Qt/qml/UM/Preferences/ManagementPage.qml
UM/Qt/qml/UM/Preferences/PluginsPage.qml
UM/Qt/qml/UM/Preferences/PreferencesDialog.qml
UM/Qt/qml/UM/Preferences/PreferencesPage.qml
UM/Qt/qml/UM/Preferences/SettingVisibilityCategory.qml
UM/Qt/qml/UM/Preferences/SettingVisibilityItem.qml
UM/Qt/qml/UM/Wizard.qml

This PR fixes text rendering in system-themed qml by rounding fractional widths and heights. 
Depending on window/dialog sizes, Label elements could be rendered at fractional pixel offsets. The Text.NativeRendering renderType does not handle that nicely, leading to ugly font rendering on Windows and OSX. In an attempt to fix this, some Labels were switched to Text (which uses Text.QtRendering rendertype). Unfortunately this leads to font-rendering that is distinctively non-native on Windows. Furthermore, Text does not use the system-themed colors used by Label, leading to unreadable text in dark-themed systems (black on black).
By rounding all widths/heights to whole pixels, Text.NativeRendering can be used without rendering problems.
See https://github.com/Ultimaker/Cura/issues/1748 for …

Fix system text rendering

---

UM/Qt/QtApplication.py
UM/Qt/qml/UM/Dialog.qml
UM/Qt/qml/UM/Preferences/PluginsPage.qml
UM/Qt/qml/UM/Preferences/PreferencesPage.qml
UM/Qt/qml/UM/Preferences/RenameDialog.qml
UM/Qt/qml/UM/Preferences/SettingVisibilityItem.qml
examples/definition_viewer/main.qml

This PR attempts to solve the Hi DPI issues on both OSX and Windows. OSX apparently no longer needs the Screen.devicePixelRatio workaround when specifying pixel sizes, but Windows certainly does.
This PR is for testing an approach where instead of using Screen.devicePixelRatio, we use a Uranium-supplied screenScaleFactor. This context variable was introduced a couple of releases ago, but never used.
When testing, also use the related Cura PR (https://github.com/Ultimaker/Cura/pull/2484), as most occurrences where a fix is needed are in the Cura repo.
For additional discussion see https://github.com/Ultimaker/Cura/commit/7bc715a9bd5e61efcfef4b54f7d004b3f6248f5a#commitcomment-24539576

Fix screen scale factor

---

UM/Qt/Bindings/Theme.py
UM/Qt/qml/UM/MessageStack.qml

This should fix the garbled character on MacOS. Font sizes will now be calculated in points instead of pixels.

set the font size to points instead of pixels

---

UM/Qt/qml/UM/Preferences/PluginsPage.qml

This PR fixes the Plugins pane of preferences so it is no longer possible to disable required plugins by clicking on their names. Previously only the checkbox would be disabled for required plugins.
Contributes to https://github.com/Ultimaker/Cura/issues/2569

Disallow disabling plugins by clicking their name

---

UM/Settings/ContainerStack.py
UM/Settings/SettingFunction.py

CURA-4358
- Make getProperty() and getRawProperty() in ContainerStack to be
evaluation-context-aware.
- Allow getRawProperty() to skip some containers if this info is
provided by the context.
- SettingFunction can now override operators with those provided in the
evaluation context.

Add evaluation context processing for ContainerStack and SettingFunction

---

UM/Qt/QtApplication.py

This fixes the problem where QML warnings/errors are not ending up in the log files on windows, making debugging harder, as they end up in the event viewer of windows, and thus are not mixed with our normal log files.

Use the Uranium logging framework to log QML warnings, instead of using stderr.

---

UM/Qt/QtApplication.py

So plugins no longer have to touch our privates (_engine) and creation is done in the same way for all objects. As there are some notes/tricks to this.
I noticed that you have to keep a reference to the created "context" item, else it gets garbage collected and this causes some QML components to fail (for example buttons no longer respond to clicks).
The extension plugin example does this wrong for example:
https://github.com/Ultimaker/UraniumExampleExtensionPlugin/blob/master/ExampleExtension.py#L58
Which costed me quite some time to figure out why my qml window was misbehaving.
To give some examples for this new function, the function in the example can be replaced with:
```
def _createDialogue(self):
return Application.getInstance().createQmlComponent(os.path.join(PluginRegistry.getInst …
```

Add a function to create a QML component.

---

UM/Settings/InstanceContainer.py

This PR fixes loading values from INI files when they start with a semicolon, eg comments in start/end gcode.
Caveat: this removes the possibility to add comments in the INI files, since they would be considered part of the values now. In the past 2 years there has not been a single cfg.ini file in the Cura distribution that uses ; for non-value comments. 
Fixes https://github.com/Ultimaker/Cura/issues/1237

Fix loading values that start with a semi-colon

---

UM/Settings/Models/SettingPropertyProvider.py

This PR fixes a crash when switching to a machine for which a setting is not defined which is defined for the current machine. This can happen if a machine defines settings in its def.json file.
I don't remember this being an issue in 3.0, so that would make the crash a regression.

Fix a crash when a definition for a setting is not available

---

UM/Settings/Models/SettingPropertyProvider.py

Fixes: When modifying a setting value, the reset icon appears. If you put the value back manually to the original value, the reset icon will still remain. This is observed on Settings that are boolean and Limit to Extruder only... but it may be possible that there are more...

Cura 5059 reset icon visibility

---

resources/shaders/composite.shader

When running Cura with closed-source Mali drivers it is needed to define the precision for float. I'm not sure (as I wrote this some time ago), but this was not needed if you are using software rendering via LLVM pipe.
The same effect can happen, when using other GLESv2 closed-source drivers.
- Related to https://github.com/Ultimaker/Uranium/pull/116

[WIP] GLESv2: Defining precision for float

---

UM/Tool.py
plugins/Tools/MirrorTool/MirrorTool.py
plugins/Tools/RotateTool/RotateTool.py
plugins/Tools/ScaleTool/ScaleTool.py
plugins/Tools/TranslateTool/TranslateTool.py

This PR fixes an issue where if the user selects both a child object and its parent, the child object effectively gets transformed twice. 
Steps to reproduce:
* load two objects
* group the two objects
* select the group AND one of the children (ctrl+shift-click the child)
* move/rotate/scale the selection
Expected result:
The group is transformed, and the child is automatically transformed by its parenting in the scene graph
Actual result:
The group is transformed, the child is transformed twice as much as the group
Additional info:
The issue also affects Support Eraser meshes

Prevent selected children of selected nodes being transformed twice

---

UM/ConfigurationErrorMessage.py
UM/Resources.py
UM/Settings/ContainerStack.py
plugins/LocalContainerProvider/LocalContainerProvider.py

This introduces a ConfigurationErrorMessage class that aggregates and shows errors in the user's configuration. When deserialisation fails, the error is shown to the user.
The message also allows the user to reset their configuration to factory defaults, as a reliable (but destructive) way to recover from the error.
Implements CURA-5045.

Show configuration errors

---

UM/Version.py
tests/TestVersion.py

SemVer is not only X.X.X, but can also be X.X.X-SOMETHING.X. A version is higher when SOMETHING is the **same** as the other version and the X after SOMETHING is higher again.

Add support for SemVer postfixes in Version.py

---

CMakeLists.txt
LibraryDir.py.in
UM/Application.py

If LIB_SUFFIX is used when invoking CMake, we have to let Cura know where the
plugins can be found.
Fixes #347

Fix a startup crash when using Cura.

---

UM/Application.py
UM/PackageManager.py
UM/Qt/QtApplication.py

Uranium is currently completely broken, because the loading of plug-ins depends on this new Package Manager which is only in Cura.
This PR moves the code to Uranium and adds a CuraPackageManager class that overwrites a very small amount of that data for Cura specifically.
This PR depends on https://github.com/Ultimaker/Cura/pull/3850 and vice versa. Merge them at the same time.

Move package manager to Uranium

---

UM/Resources.py
UM/VersionUpgradeManager.py
plugins/FileLogger/FileLogger.py

This PR stops VersionUpgradeManager from opening and reading Cura.log (multiple times!) to see whether it needs updating. The application log can not be upgraded, so this is a waste of memory and cpu cycles.
Ignoring a 220 MB accumulated Cura.log file bumped the boot time down from more than 22 seconds to less than 10 on my system.

Ignore cura.log when checking for files to be updated

---

UM/PackageManager.py

Packages built with libCharon have package.json under /package.json. This change keeps compatibility with both options (by using the same mechanism as searching for license files).

Search for all files ending in package.json to make sure it's found

---

UM/Scene/Scene.py

Before, this feature was broken, since it showed 2 messages every time the file is modified and the "Reload" button did nothing when clicking.
Both the double message and the button are fixed in this PR.

Fix the watched files feature

---

plugins/Tools/CameraTool/CameraTool.py

This is a tiny tweak to make the camera more responsive when you rotate the camera.
When you right click and drag in the 3D view we only start rotating the camera if you move enough. This is because the user may want to just right click without moving the camera to access the context menu. When you right click and you don't have the hands of a surgeon, you may move the mouse cursor a few pixels while doing so but if we then start moving the camera immediately, you won't get the context menu you wanted.
It makes it slightly harder to access the context menu of the main window if you have Parkinson's disease, or just a very sensitive touch pad that makes you use a gesture to right click. But I think that was just way to wide of a drag distance and it's still pretty easy to right-click …

Reduce drag distance

---

UM/Settings/ContainerRegistry.py

If a dirty container was "removed," don't save it. Doing so creates copies of the file which was intended to be removed, and also they become conflicts if the user ever tries to install that package again.

CURA-5621 Don't save "removed" containers

---

UM/Settings/Models/SettingDefinitionsModel.py

descendant setting. Instead look at the current container.

Don't fallback to the global stack when checking the visibility of a

---

UM/PluginRegistry.py
plugins/ConsoleLogger/plugin.json
plugins/FileHandlers/OBJReader/plugin.json
plugins/FileHandlers/OBJWriter/plugin.json
plugins/FileHandlers/STLReader/plugin.json
plugins/FileHandlers/STLWriter/plugin.json
plugins/FileLogger/plugin.json
plugins/LocalContainerProvider/plugin.json
plugins/LocalFileOutputDevice/plugin.json
plugins/Tools/CameraTool/plugin.json
plugins/Tools/MirrorTool/plugin.json
plugins/Tools/RotateTool/plugin.json
plugins/Tools/ScaleTool/plugin.json
plugins/Tools/SelectionTool/plugin.json
plugins/Tools/TranslateTool/plugin.json
plugins/UpdateChecker/plugin.json
plugins/Views/SimpleView/plugin.json
tests/PluginRegistry/EmptyPlugin/plugin.json
tests/PluginRegistry/PluginNoVersionNumber/plugin.json
tests/PluginRegistry/TestNested/TestPlugin2/plugin.json
tests/PluginRegistry/TestPlugin/plugin.json
tests/Settings/ContainerTestPlugin/plugin.json

This PR increases the API Version and removes a hack to disallow certain versions of the OctoPrint plugin.
Commit 46b6c7e33e08154260db17eb1b8707604fa66d99 changed the way metadata for container stacks is handled in a way that makes certain plugins (such as the OctoPrintPlugin) incompatible with master. I can change my plugins to be compatible again, but I cannot change the 10k+ installations already in the field, so these must be invalidated by changing the plugin API version*. This means that all plugins must be updated before the next release (even if only updating their API versions, if there are no other incompatibilities).
*: note that I have already implemented a precaution in OctoPrintPlugin so it does not load with versions of Cura it has not been tested against at the time of …

Increase APIVersion and remove OctoPrint hack

---

resources/i18n/pl_PL/uranium.po

Translation was incomplete, phrases related to functions implemented after version 3.3 were missing. I have translated all missing phrases in Polish translation of files cura.po, uranium.po and fdmprinter.def.json.po. For now, translation is complete. I tried running it on Cura 3.5 beta and I can't encounter any issues.

Complete Polish translation for version 3.5

---

UM/VersionUpgradeManager.py

We don't need to know when a file is not being updated. Also add the `packages.json` file to the list of files that don't need updating.

[master] Remove debugging message that fills the logs

---

plugins/ConsoleLogger/__init__.py
plugins/FileLogger/__init__.py
plugins/LocalFileOutputDevice/__init__.py
plugins/Tools/CameraTool/__init__.py
plugins/Tools/SelectionTool/__init__.py
plugins/UpdateChecker/__init__.py

This PR removes unused imports and declaration of i18n in plugins. There's also a PR for Cura that does the same thing there.

Remove unused import and declaration of i18n in plugins

---

UM/Application.py
UM/LockFile.py
UM/Settings/ContainerRegistry.py
UM/VersionUpgradeManager.py
tests/Settings/conftest.py
tests/TestTools.py
tests/conftest.py

The Windows API is now used to create and delete the lock file. This file is now created with a flag DELETE_ON_CLOSE that deletes the file when closing or when the application gets interrupted.

Improve lock file management in Windows

---

plugins/UpdateChecker/UpdateChecker.py
plugins/UpdateChecker/UpdateCheckerJob.py

When automatically checking for updates, only show the same update once. So it'll say once that there is an update for 3.5.1, but not again unless you manually check for updates. Once 3.6 rolls around, it'll show that there is an update again.
This is in line with how most update systems behave in other applications.

Only show update once

---

UM/LockFile.py

Remove a time offset that was probably added for debugging purposes that increased the timeout in 100 seconds.
Contributes to CURA-5850.

Fix timeout in the lock file

---

UM/Settings/Models/DefinitionContainersModel.py

This PR fixes passing definitioncontainers metadata to QML. For fully loaded definitions, the metadata is an OrderedDict which does not pass to QML correctly. This became apparent in Cura here:
https://github.com/Ultimaker/Cura/pull/4498#issuecomment-434966876

Fix passing definitioncontainers metadata to QML

---

UM/Qt/QtApplication.py

This PR actively removes the tray icon before the application is shut down, so the tray icon does not get orphaned. Without this PR, an orphan tray icon is left behind each time Cura is shut down.

Remove tray icon while the application is still alive

---

plugins/FileHandlers/STLReader/STLReader.py

For some reason, I have trouble with NumPy-STL provided by Ubuntu when using my PPA.
Therefore took some time digging into this issue and added this fallback, because the legacy code works (still) just perfectly fine!

STLReader: Adding fallback to legacy code

---

UM/Math/Polygon.py
tests/Math/TestPolygon.py

Need this polygon operation for a fix in Cura (child-nodes like support-blocker where arranged separatelty when 'Arrange Models' was selected).

CURA-6120 arrange child nodes fix

---

UM/Application.py

If there is a symlink to the installation directory and it appears before the actual installation directory on the user's PATH, it would get a wrong path for `sys.argv[0]`. This then messes up the install location which consequently messes up the data and config storage directories.
This solution is provided by CapnKernel and should resolve the symlink so that sys.argv[0]='/usr/bin/python3' again and the storage data and config storage directories become something like /usr/share/... again.
This should fix https://github.com/Ultimaker/Cura/issues/5290 .

Fix install prefix when installing in symlinked directory

---

UM/Qt/QtApplication.py
UM/View/GL/OpenGLContext.py

This PR checks if the best detected OpenGL version isn't using software rendering provided by the OS instead of a GPU renderer. With newer versions of Qt on OSX (and Linuxes ?), requesting a 4.1 context on a GPU that does not support hardware accelerated 4.1 rendering results in a software rendered context which is much slower than a hardware accelerated 2.0 context. This PR detects software rendering OpenGL 4.1 renderers, and falls back to OpenGL 2.0 instead. 
Contributes to https://github.com/Ultimaker/Cura/issues/4505 (CURA-6092)
This will need testing on many systems.

Opt to use OpenGL 2.0 instead of software rendered OpenGL 4.1

---

UM/Math/Matrix.py
UM/Math/Quaternion.py
UM/Operations/SetTransformOperation.py
UM/Scene/Camera.py
UM/Scene/SceneNode.py
UM/View/RenderBatch.py

On my machine, this made the decompose step 67% faster. This, in turn, made all scene operations 24.4% faster. Mileage may vary from system to system but I'm pretty sure that this should be better on most systems.

Switch out the implementation of decompose for a faster variant

---

tests/benchmarks/conftest.py

https://docs.pytest.org/en/latest/deprecations.html#config-warn-and-node-warn

Support Pytest 4, config.warn is no more

---

UM/Scene/Camera.py
UM/View/RenderBatch.py
resources/shaders/color.shader
resources/shaders/default.shader
resources/shaders/object.shader
resources/shaders/platform.shader
resources/shaders/selection.shader
resources/shaders/toolhandle.shader

Turns out doing the model-view-projection multiplication matrix repeatedly in the shader is still faster than doing it once per render in python.
Edit: Don't merge before the 4.1 branch is made! / CURA-6477

Shader optimization

---

tests/Math/TestVector.py

Fixes https://github.com/Ultimaker/Uranium/issues/496

Allow approximate equality in TestVector.test_normalize for smaller arches

---

UM/Qt/qml/UM/RecolorImage.qml

Replace ShaderEffect with ColorOverlay. As far as I can tell, the visual effect is equivalent. Tested on Linux using Qt 5.10 and Qt 5.13.
Possibly fixes https://github.com/Ultimaker/Cura/issues/6008.

ShaderEffect crashes on Linux with Qt 5.13 so replace with ColorOverlay.

---

UM/Qt/Bindings/PointingRectangle.py

Fixes one of the problems discussed in https://github.com/Ultimaker/Cura/issues/6008.

Set border_node's geometry and material before appending it to paint_node

---

UM/Settings/ContainerRegistry.py

This prevents creating a whole lot of ContainerQuery objects which improves performance as well as the effectiveness of the cache.

Don't create query object when using ID shortcut

---

UM/Qt/QtMouseDevice.py

This PR fixes the behavior of tools (translate, rotate, scale) when dragging the mouse over QML elements that contain a MouseArea (such as SettingItems in the sidebar, or the object list) during the operation.
Steps to reproduce the issue:
* load a model
* select the model
* drag the red axis, all the way over the settings float/sidebar
Result:
While over parts of the settings floater, the model jumps to the left of the window, until the pointer is dragged off the QML element that contains a MouseArea.

Fix tools when dragging over mouseareas

---

UM/View/GL/OpenGL.py
plugins/Tools/RotateTool/RotateTool.py
plugins/Tools/RotateTool/RotateTool.qml
resources/shaders/selection.shader

The new feature to select a face and then rotate the model so that the face is at the bottom relies on a GLSL feature (gl_PrimitiveID) that isn't in versions of GLSL < 1.5. Therefore, for those early versions of GLSL, the select face feature is hidden.

Disable select face feature when gl_PrimitiveID not supported by GLSL.

---

UM/Mesh/MeshData.py
UM/Operations/MirrorOperation.py
UM/Scene/SceneNode.py

A mirror operaion was done via 'scale', but that inverts the normals, which might give some issues (for example, 'Make Overhang Printable' wouldn't work correctly).
part of CURA-6924

Fix normals after mirroring.

---

UM/Controller.py

Just noticed that the error message will keep mentioning that it couldn't default to the tool called TranslateTool, even if the tool is not our fallback tool at this moment.
This change will simply make the warning mention the currently set fallback tool.

Controller: Updating warning message

---

UM/PluginRegistry.py

This PR speeds up the loading of plugins on start. The original code contains recursion which I think nobody really understood and the folder cache variable did not work. Because of this, each successive loaded plugin would take longer to be located.
On my system, the "Loading plugins" stage took 47 seconds, which has now been reduced to 27 seconds. The original code was especially cumbersome because it traversed every .git and pycache folder for each plugin load, which on my system caused the _locate_plugin method to be call hundreds of thousands of time on launch.
Edit: this PR now includes the optimization in #538

Speed up loading of plugins on start

---

plugins/FileHandlers/OBJReader/OBJReader.py

It now recognises and processes a trailing \ but only if it is separated from the element
before, so 123 \ will work and 123\ won't.
Fixes https://github.com/Ultimaker/Cura/issues/6721
I don't claim this is a great solution but it works in this case.

Quick fix for obj file reader so it can cope with line continuation.

---

UM/Qt/Bindings/MainWindow.py
UM/Qt/QtRenderer.py

Previously we would also re-render the entire scene if a QML object required some re-drawing. We can save a fair bit of time if we don't do this.
CURA-6247

Only re-render the scene when it's actually needed

---

UM/PluginRegistry.py
UM/Qt/qml/UM/Preferences/SettingVisibilityCategory.qml
UM/Settings/Models/SettingDefinitionsModel.py
tests/Settings/TestSettingDefinitionsModel.py

Adds a menu item in the Custom Print Settings list to collapse all categories
Does not work when a search is active. See Accompanying Cura PR.

CURA-6959_collapse_categories

---

UM/PackageManager.py

This PR adds one more field to the `packages.json` file called "dismissed". There shall be all the packages that the decided to dismiss, by clicking the button in the Compatibility Dialog.
It's used in https://github.com/Ultimaker/Cura/pull/6961

CURA-7090/Added a "dismissed" package logic.

---

UM/Qt/Bindings/MainWindow.py

This PR fixes restoring the window to its "normal" size and location after closing it in maximized state. In addition to that, it also excludes the maximised/normal state of the window when the `restore_window_geometry` preference is unset.
Fixes https://github.com/Ultimaker/cura/issues/6904
Steps to reproduce issue that is fixed by this PR:
* load Cura and set the window to a custom size and position
* make sure the "Restore window position on start" option is checked
* restart Cura
-> windows is correctly placed in the custom position and size
* now maximize the window
* restart Cura
-> window is (correctly) maximized on startup
* now restore the window to not maximized
-> window (incorrectly!) does not restore to previous custom position and size

Fix restore window size if application is closed maximized

---

UM/PackageManager.py

Added two functions to the Package Manager:
1. A function that marks a package as "dismissed" and puts it in a list called `dismissed` in the `packages.json` file in the user's local data folder.
2. A function that re-evaluates the dismissed incompatible packages, and if needed removes them from the dismissed_packages list.
Is being used in: https://github.com/Ultimaker/Cura/pull/7011

CURA-7090/Added function reEvaluateDismissedPackages() in the Package Manager

---

UM/Qt/QtApplication.py
UM/View/GL/OpenGLContext.py

During the windows bug fix, some hidden preferences where created that we decided to leave in. This makes them less ad-hoc.

Make hidden OpenGL detect prefs. less confusing.

---

UM/PackageManager.py

See https://docs.python.org/3.9/whatsnew/3.9.html#removed
> The encoding parameter of json.loads() has been removed. As of Python 3.1,
> it was deprecated and ignored; using it has emitted a DeprecationWarning
> since Python 3.8.

Remove deprecated/ignored encoding parameter of json.loads()

---

UM/View/GL/OpenGL.py
UM/View/RenderBatch.py

If a mesh is drawn with a range, make sure the current range is applicable to that mesh. (But don't reset the range to the max of that mesh.)
What this does is fix the OpenGL crash that you can get when the max is over the index-buffer length -- but without messing up the sim. sliders.
CURA-7161

CURA-7161 Fixes simulation sliders yet again.

---

UM/Trust.py
scripts/createkeypair.py
scripts/signfile.py
scripts/signfolder.py

- Don't skip symbolic links anymore when walking over a directory, either when generating a signature file for a folder, or when validating.
- There was almost no documentation. Now there rather more.

'Trust' Updates

---

UM/Mesh/MeshData.py

Looks like Python is getting more strict and wants more clear instructions how "if (not) <array>" shall be interpreted.
Since it looks like we are checking whether vertices are None, I just rewrote it so the logic keeps the same.
Here the original error message:
```
2020-02-23 12:56:30,352 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [67]:   File "/usr/lib/python3/dist-packages/UM/Mesh/MeshData.py", line 336, in getFaceNodes
2020-02-23 12:56:30,352 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [67]:     if not self._indices or len(self._indices) == 0:
2020-02-23 12:56:30,353 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [67]: ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

MeshData: Making a None check the other way around

---

UM/Settings/Models/SettingVisibilityHandler.py

The problem: When infill mesh is set, wall_thickness and top_bottom_thickness are added to the settings.
Then these settings are set to visible on the visibility_handler.
It appears however, that the visibility_handler considers all added settings to be visible. It thus concludes that no UI update is necessary because the settings are already added.

CURA-7211_pos_infill_defaults_0

---

UM/PluginRegistry.py
UM/Trust.py
tests/TestTrust.py

Adding a public key to Cura revealed that fail fast crashes weren't happening when an untrusted plugin was about to be loaded. This fixes that. (Here of course since plugins are in Uranium as swell.)
(See also https://github.com/Ultimaker/Cura/pull/7182 )

CURA-7016 Fix Trust and tests thereof.

---

UM/Settings/SettingFunction.py
tests/Settings/TestSettingFunction.py

This makes the setting function a whole lot more paranoid! It contains both a white and a black list. All setting calls must be on the white list and a number of strings are blacklisted. 
CURA-7169

Prevent code injection in setting functions

---

UM/Settings/SettingFunction.py

This PR fixes checking non-string constants in Python 3.8. #587 introduced a regression because it incorrectly assumes all constants are strings.
Fixes https://github.com/Ultimaker/Cura/issues/7335

Fix visiting non-string constants in Python 3.8

---

UM/Application.py
UM/OutputDevice/OutputDeviceManager.py
UM/Qt/Bindings/OutputDeviceManagerProxy.py

This PR adds a preference to the OutputDeviceManager to remember which outputdevice is selected between sessions.
https://github.com/Ultimaker/Cura/issues/7168

Remember the last used output device between sessions

---

UM/Mesh/ReadMeshJob.py
UM/Scene/SceneNode.py

Add the node id that represents the objectId from inside the 3mf file. This can now be used as an identifier of the node when refreshing the object, to refresh the correct object from the 3mf file.
Requires https://github.com/Ultimaker/libSavitar/pull/24
Merge this along with https://github.com/Ultimaker/Cura/pull/7384

Cura 7333 fix reloading 3mf files with many objects

---

plugins/FileHandlers/OBJReader/OBJReader.py

I've made a fix here that fixes loading meshes that contain vertex coordinates, but not normal vectors. Previously this would crash with an IndexError.
The format for a face is as follows:
f v1/t1/n1 v2/t2/n2 v3/t3/n3
The part after a slash is optional. You could also have faces like this, without the normals:
f v1/t1 v2/t2 v3/t3
Or even a face like this, with just the vertices and no textures:
f v1 v2 v3
However it's not possible to have a face with vertices and normals but no textures:
f v1/n1 v2/n2 v3/n3
This gets interpreted as a face with vertices and textures.
When given a face with just vertices and textures, our old code would give an IndexError saying that the normal vectors are out of range. That would be correct since it only stored -1 there. This fixes that by turning the …

Fix for loading OBJ files without normals, and speed optimisations

---

UM/View/GL/ShaderProgram.py

First this will get rid of the messages below and second it is the correct way to check the equality of numbers.
Here is the difference:
```
>>> x = int(1000.0)
>>> x is 1000
False
>>> x = 1000
>>> x is 1000
False
>>> x == 1000
True
```
```
if common_path is "" or not common_path.startswith(install_prefix):
/usr/lib/python3/dist-packages/UM/View/GL/ShaderProgram.py:340: SyntaxWarning: "is" with a literal. Did you mean "=="?
elif type(value) is list and type(value[0]) is list and len(value[0]) is 4:
/usr/lib/python3/dist-packages/UM/View/GL/ShaderProgram.py:342: SyntaxWarning: "is" with a literal. Did you mean "=="?
elif type(value) is list and len(value) is 2:
/usr/lib/python3/dist-packages/UM/View/GL/ShaderProgram.py:344: SyntaxWarning: "is" with a literal. Did you mean "=="?
elif …
```

View.GL: Correcting equality check of numbers

---

UM/Scene/ToolHandle.py
UM/View/SelectionPass.py
plugins/Tools/RotateTool/RotateTool.py
plugins/Tools/RotateTool/RotateToolHandle.py

This PR adds 3 pairs of arrow widgets to the Rotate ToolHandle, to rotate objects by exactly 90 degrees. To do so, it adds a way for ToolHandle instances to register additional widgets/controls. In this PR, the arrow widgets can still be dragged like the axes, but when clicked they rotate the model by +/- 90 degrees around the relevant axis.
This feature covers a large chunk of the usecases for a panel with degree value boxes (https://github.com/Ultimaker/Cura/issues/2779) without the added can of worms that would open.

Add widgets to Rotate by 90 degrees

---

UM/Scene/ToolHandle.py
plugins/Tools/RotateTool/RotateTool.py
plugins/Tools/RotateTool/RotateToolHandle.py

This PR fixes a crash when right-clicking while hovering over toolhandle extra widgets such as the rotate-by-90-degrees arrows of the RotateTool that were added in https://github.com/Ultimaker/Uranium/pull/612. The original implementation used strings (enum name) as identifiers for the extra widgets. Instead, ExtraWidgets now identify as ints (enum value).
Fixes https://github.com/Ultimaker/Cura/issues/7867

Fix crash when clicking right mousebutton over toolhandle extra widgets

---

UM/Settings/SettingFunction.py

String constants are represented as ast.Constant objects starting with
Python 3.8.
Fixes #619.

Handle indexing on Python 3.8 AST string constants correctly

---

UM/Settings/ContainerRegistry.py
tests/Settings/TestContainerRegistry.py

If a container is partial (only metadata) loaded it shouldn't have to
load the container before removal. The emitted RemovedContainer signal
expects a container to be passed along with it. This will be an
EmptyInstanceContainer containing the metadata of the container.

Cura 6253 fix remove container that requires to load a container first

---

UM/Math/Polygon.py

This is a helper function that's necessary for the implementation of shrinkage compensation.
Contributes to issue CURA-7118.
Please consolidate discussions about the architecture of shrinkage compensation to the CuraEngine PR: https://github.com/Ultimaker/CuraEngine/pull/1316

Shrinkage compensation: Add a scale function for polygons

---

UM/PluginRegistry.py
UM/Trust.py

Unless explicitly requested (e.g. in DEBUG mode), Trust should not follow symlinks when checking the plugin signatures.
The enterprise plugins should not contain any symlinks anyway.
Merge along with https://github.com/Ultimaker/Cura/pull/8499.
CURA-7735

CURA-7735: Make symlink following optional when checking the plugin signatures

---

UM/PluginRegistry.py

In particular an application might want to load the logging plug-ins first. Currently Cura manually calls the loadPlugin function for ConsoleLogger, and then ConsoleLogger is also loaded again later which is causing warnings. This prevents that because Uranium knows which plug-ins are pre-loaded and will not attempt to load those again.
This is a partial solution. A complete solution would be to allow plug-ins to depend on other plug-ins. All plug-ins that log things would then need to depend on the logger plug-ins. That system is more complex though so I'll not implement that until it's deemed necessary.
Contributes to issue CURA-7501.

Add option to load certain plug-ins before the rest

---

UM/Operations/GravityOperation.py
UM/Operations/LayFlatOperation.py
plugins/Tools/RotateTool/RotateTool.py

Drop down to buildplate after lay flat or align face to build-plate, even if always drop down is disabled.
Partially fixes Ultimaker/Cura#8746 as well.

[CURA-7872] Always drop down in lay-flat operations.

---

UM/Settings/SettingInstance.py

When you set environment variable URANIUM_TRACE_SETTINGINSTANCE and run Cura you get fatal error:
```
2020-11-25 09:44:09,862 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
2020-11-25 09:44:09,867 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
2020-11-25 09:44:09,871 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "X:\4.8-exe\build\inst\lib\python3.5\site-packages\cura\CuraApplication.py", line 1063, in event
2020-11-25 09:44:09,875 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "X:\4.8-exe\build\inst\lib\python3.5\site-packages\UM\Qt\QtApplication.py", line 464, in event
2020-11-25 09:44:09,880 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File …
```

Fix Cura error with URANIUM_TRACE_SETTINGINSTANCE

---

UM/Qt/QtApplication.py

Turns out isVisible (the QtApplication function) was never called, so _main_window.visible was never called, so no-one realized that this latter one didn't exist. But _main_window _also_ has a isVisible (function not property) so now that is called by the QtApplication isVisible (property) instead.

Replace non-existant property visible with isVisible.

---

UM/FileHandler/FileReader.py
UM/FileHandler/ReadFileJob.py

Otherwise the user could infer valid, but empty file (workspace project for example) is corrupt.

[CURA-7996] Possible to distinguish between empty and corrupt files.

---

UM/Qt/QtApplication.py
UM/Scene/Scene.py
UM/Scene/SceneNode.py

We need the scene to store metadata in order to retain metadata from scenes in 3MF documents.
Contributes to issue CURA-7615.

Allow the scene to store metadata

---

UM/FileHandler/FileHandler.py
UM/Mesh/MeshFileHandler.py
UM/Workspace/WorkspaceFileHandler.py

The add_to_recent_files boolean will now be passed around as a variable to the FileHandlers. This makes it clearer whether the file should actually be added to the Recent Files list when it is being opened.
CURA-7996

CURA-7996: Fix trying to open deleted files from the recent files list

---

UM/Settings/Models/SettingDefinitionsModel.py

This PR fixes the expanded/collapsed indicator arrow for setting categories in setting views. It was broken in 905e8eb5b44fa6d16310aad80bec7ced32455b02. Reverting that change may have a performance hit, so some profiling may be in order.
Fixes https://github.com/Ultimaker/Cura/issues/8283, CURA-7692

Fix showing expanded/collapsed indicator arrow for setting categories

---

UM/Settings/SettingDefinition.py
tests/Settings/TestSettingPropertyProvider.py

When handling a float setting with a calculation, I have been getting the following error in Cura.log:
```
20:33:42,995 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [66]: An uncaught error has occurred!
20:33:42,999 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: Traceback (most recent call last):
20:33:43,004 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "X:\4.8-exe\build\inst\lib\python3.5\site-packages\UM\Settings\Models\SettingPropertyProvider.py", line 373, in _update
20:33:43,007 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]:   File "X:\4.8-exe\build\inst\lib\python3.5\site-packages\UM\Settings\Models\SettingPropertyProvider.py", line 430, in _getPropertyValue
20:33:43,011 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [69]: …
```

Fix "TypeError: type str doesn't define __round__ method"

---

UM/PluginRegistry.py

Previously it would just load the first plugin that it encountered (instead of looking at the highest version). In some cases this would be the bundled plugin in other it would be the installed version (regardless if it's version number was higher or not)
CURA-8033

Fix being unable to upgrade bundled plugins

---

UM/OutputDevice/OutputDeviceManager.py
UM/OutputDevice/ProjectOutputDevice.py
plugins/LocalFileOutputDevice/LocalFileOutputDevice.py
plugins/LocalFileOutputDevice/LocalFileOutputDevicePlugin.py

Previously, enabling/disabling a project output device would not reflect the change in the actual output devices list.
Now, if a project output device gets disabled, it will be automatically removed from the output_devices list if it was added there in the first place. When it gets enabled again, the device is readded to this list, making it available to be selected from the OutputDevicesActionButton in the bottom right.
CURA-7903

CURA-8050: Remove project output devices from the list when they get disabled

---

UM/TaskManagement/HttpRequestManager.py

Calling readAll() when logging the reply during an error, consumes the content of the QNetworkReply making it unavailable to the error_callback called later. To fix that, we can use peek() instead for reporting the error in the logs.
CURA-8066

CURA-8066: Fix consumption of HTTP reply body in HttpRequestManager

---

UM/Qt/qml/UM/MessageStack.qml
UM/Qt/qml/UM/Preferences/ManagementPage.qml

In Qt5.15 the Connections items should not be using the "on < signal >" format since it is depricated.
They should have the format function "on< signal >(arguments)" instead.

Fix QML warnings produced due to signal calls in Connections

---

UM/Qt/qml/UM/Preferences/PreferencesDialog.qml

Since single selection is already default, you wouldn't expect this to be necesary, but single selection is appearantly only for mouse clicks, not for the inactive selection? Must be a bug I guess. Anyway it works now.
fixed as part of CURA-8127

Prevent seemingly multiple selected tabs in prefs-screen.

---

UM/OutputDevice/ProjectOutputDevice.py

The OutputDevice class is decorated with the signalemitter decorator, which allows it to declare the instance signals outside the `__init__` function. However, the ProjectOutputDevice was not decorated similarly, which was causing it to have the writeSignals between ProjectOutputDevices being shared. Therefore, when we emitted the writeStarted signal (which triggers the sending of the SliceInfo) in the LocalFileOutputDevice, it was being triggered also for other ProjectOutputDevices. Pretty weird issue.
CURA-8164

CURA-8164: Fix slice info being send multiple times

---

UM/OutputDevice/OutputDeviceManager.py

If the project output device was disabled at startup, the write signals were still connected. Then, when the device was getting enabled, its write signals were getting connected again, leading to issues like sending the slice info twice when the device was being used to write to a file.
This commit fixes that by making sure that the signals on startup are being connected ONLY if the device is enabled.
CURA-8164

CURA-8164: Don't connect the signals if the device is disabled on startup

---

plugins/Tools/ScaleTool/ScaleTool.py

277 crashes reported against 4.8 according to sentry -- but no indication as to what the _original_ matrix was that went in that causes this

[CURA-8005] Crashes reported, but cause unknown: defensive code + extra log.

---

UM/CentralFileStorage.py
tests/TestCentralFileStorage.py

This is a pull request that adds new functionality to Uranium: Central File Storage. This functionality allows the programmer to store a file in a central location that is not dependent on the version number of the application he's running. It is a requirement for using plug-ins with large files, as the version upgrade system would copy those plug-ins each time the user upgrades the application. Using this central file storage, the programmer can move a big file out of the plug-in directory, reducing the file size of the plug-in directory.
There is a new class `CentralFileStorage` which collects two methods: `store` and `retrieve`. The `store` function stores a file in the central location, physically moving it away from the directories that get copied for each version. The `retrieve` …

Central File Storage

---

UM/Qt/Bindings/Theme.py
UM/Qt/qml/UM/MessageStack.qml
UM/Qt/qml/UM/Preferences/SettingVisibilityCategory.qml
UM/Qt/qml/UM/Preferences/SettingVisibilityItem.qml
UM/Qt/qml/UM/Wizard.qml
plugins/Tools/MirrorTool/__init__.py
plugins/Tools/RotateTool/RotateTool.qml
plugins/Tools/RotateTool/__init__.py
plugins/Tools/ScaleTool/ScaleTool.qml
plugins/Tools/ScaleTool/__init__.py
plugins/Tools/TranslateTool/__init__.py

This PR adds new logic to the getIcons function allowing an icon to be stored in a subfolder. For instance different sizes. Such as is the standard within the UX department.
Since the used icons are renamed according to the conversion table and practice of the UXers this is also updated in the code.
Also, check PR ultimaker/cura#9716

Cura 8010 icon size

---

UM/Mesh/MeshReader.py
UM/Scene/SceneNode.py

This keeps track of each mesh what MIME type the mesh was loaded from, for the purpose of being able to send that information as anonymous usage statistic to Ultimaker.
It is accepted that meshes generated in other ways (e.g. from the Support Blocker plug-in) don't get an assigned MIME type.
Contributes to issue CURA-8232.

Track MIME type of opened mesh files

---

UM/CentralFileStorage.py
UM/Trust.py

Plugins that make use of the central storage can now move an entire folder without having to mention each and every file in their `central_storage.json`. So now, when an entire folder is move, the `central_storage.json` can look like this:
```json
[
[
"my_folder",
"my_folder",
"1.0.0",
"aa9125bc0121eaaa09125989832532c9c718a9b9e9ddd123"
]
]
```
CURA-8261

CURA-8261: Allow central storage to store folders

---

UM/Math/Vector.py
UM/Scene/SceneNode.py

The position of the group node itself should in theory never be used. Only include the position of the group node itself if there is no mesh data and no children to have any redeemable AABB. Then also handle child nodes that have those degenerate empty group AABBs.
Contributes to issue CURA-7873.

Fix calculating bounding box when group nodes are involved

---

UM/CentralFileStorage.py
UM/PackageManager.py
UM/PluginRegistry.py
UM/Qt/QtApplication.py
tests/TestCentralFileStorage.py

This PR changes the following:
- To make sure that the splash screen's loading wheel is not stuck while plugins are being unpacked, the unzipping of a downloaded plugin by the PackageManager now happens file-by-file. After each extracted file, the package manager calls the `processEvents()` function, which ensures that the interface gets updated (and the loading wheel keeps turning instead of getting stuck).
- Same thing now happens while the CentralFileStorage is hashing files, because hashing can take a long time and give the idea that the splash screen is stuck.
- The splash screen now displays a message regarding which plugin is currently being unpacked and which plugin is being loaded. This way big plugins don't give the idea that the startup is stuck.
Requires …

CURA-8291: Verbose plugin loading on startup

---

UM/Qt/QtApplication.py

This function can also be used during a backup to ensure that the cura.cfg that is restored from the backup does not get overridden by the previous cached preferences.
CURA-8313
Required by https://github.com/Ultimaker/Cura/pull/10022

CURA-8313: Make a function that reads the preferences from cura.cfg

---

UM/PluginRegistry.py
UM/Trust.py
tests/MimeTypes/TestMimeTypes.py
tests/TestTrust.py

In enterprise scenario's:
Before moving the files, run a quicker security check on the central storage file itself, since it could be potentially used to copy files from an elevated account (even if the plugin itself isn't run yet).
To prevent this, two things where done;
- one is that it's checked that the file that's being moved is (to) _within_ the plugin folder.
- The other is a quick 'pre-check' that doesn't scan the whole folder but only checks the integrity of the central storage file (and the manifest). This should, (and now _can_) be done _before_ moving however.
P.S. Internal ticket is also cloned as CURA-8407

[SEC-240] Add Pre-Storage Check To Trust

---

UM/Message.py
UM/Qt/Bindings/VisibleMessagesModel.py
UM/Qt/qml/UM/MessageStack.qml
plugins/LocalFileOutputDevice/LocalFileOutputDevice.py

Now the messages contain a message type, which can be one of the following:
1. POSITIVE
2. NEUTRAL (default)
3. WARNING
4. NEGATIVE
The message types determine what icon will appear next to the title of the message. 
Requires https://github.com/Ultimaker/Cura/pull/10175.
CURA-7278

CURA-7278: Differentiate warning messages in cura

---

UM/CentralFileStorage.py
UM/PluginRegistry.py
UM/Trust.py
tests/TestTrust.py

Also refactor those sorts of test into the signed folder pre-storage check, where they belong. (Otherwise a part of that security was handled by the plugin system.) Also amend unit-tests to take into account these situations. While doing that, found an oversight in the `isPathInLocation` functionality, which is by necessity now also in Trust.
SEC-240 / CURA-8407

[SEC-240] Fix items that would be copied outside of storage location.

---

UM/Qt/QtRenderer.py
UM/View/GL/OpenGL.py
UM/View/GL/ShaderProgram.py

Shaders are already treated (in frontend program) as if they where None on failure. Now actually make it so.
This is part of a bugfix that came to our attention as 'If the slice button is clicked while the context-menu is also open on that same button, Cura crashes'. Suspect it may fix more than just that. For the rest of that more specific fix, see: https://github.com/Ultimaker/Cura/pull/10210

[CURA-8412] Make creation of shader program return None on failure.

---

UM/Message.py
UM/Qt/Bindings/VisibleMessagesModel.py

Some plugins would like to be backwards compatible. In order to do that, make it possible to pass the type as a string. In order to parse it back, it's way easier if it's an Enum.
CURA-8473

Possibility for backwards compatible messages.

---

plugins/Tools/RotateTool/RotateTool.py

This PR fixes the rotation direction of the 90 degree rotation arrows in the Rotate Tool. Currently the arrows in both directions rotate the model in the same direction. They should operate in opposite directions.
Fixes https://github.com/Ultimaker/Cura/issues/10279

Fix the rotation direction of the 90 degree rotation arrows

---

resources/bundled_packages/uranium.json
tests/conftest.py

URANIUM:
* Added optional 'message_type' argument to Message.__init__
* Added Message.MessageType enum-class
* Added Message.getMessageType(self) -> MessageType
Messages can have types now, this determines the sort of icon they get for now as well.
* Added TrustBasics.isPathInLocation(location: str, path: str) -> bool
Whether a path is a sub-folder (or equal) of a given location (path).
* Changed OpenGL.createShaderProgram(self, file_name: str) -> Optional[ShaderProgram]
Now returns optional instead of 'just' a shader-program, since part of the code already expected that to be the case.
* Removed 'UpdateCheckerJob' class
Now just handled withint the UpdateCheckerJob.

[CURA-8491] Update SDK 7.6 -> 7.7 because of API changes.

---

UM/Qt/Bindings/VisibleMessagesModel.py

Some messages may already provide a QUrl as the image source. In such cases, Cura would crash because the `QUrl.fromLocalFile()` expects a string and not a QUrl as input. 
This is now accounted for to make sure that in the image source will not be converted to QUrl again.
CURA-8500

CURA-8500: Safely convert message image sources to QUrls

---

UM/OutputDevice/OutputDevice.py
UM/OutputDevice/ProjectOutputDevice.py
plugins/LocalFileOutputDevice/LocalFileOutputDevice.py

Cura was not retaining the last saved filename selected by the user after they were saving their file. This PR fixes that by making sure that the filename selected by the user in the save file dialog will update the name of the workspace (project) all around Cura.
**Note:** The stored filename is forgotten when the user loads another project file, creates a new project (Ctrl+N) or clears the buildplate (Ctrl+D).
Original feature request: https://github.com/Ultimaker/Cura/issues/10061
Required by https://github.com/Ultimaker/Cura/pull/10328.
CURA-8358

Retain the last saved filename after saving a file

---

UM/OutputDevice/OutputDevice.py
UM/OutputDevice/ProjectOutputDevice.py

When altering the name of a project when saving a project to output device A, then altering the name while saving it to output device B, then altering the name again, and _exporting_ to output device A again, the name as saved first to output device A will be the project name again, after saving the correct name via output device A.
Anyway, I made the variable static and now it shares the last saved _project_ name between all output devices, so things like that shouldn't happen again :-)

[CURA-8358/b] Fix (change name each time when) save to disk, then save to dl, then export to disk.

---

UM/Settings/DefinitionContainerUnpickler.py
plugins/LocalContainerProvider/LocalContainerProvider.py

CURA-8399 
We used to just load stuff from pickle. This meant that malicious stuff could be done if the cache was somehow compromised.

Fix Insecure deserialization of DefinitionContainer

---

UM/Settings/SettingFunction.py

Fixed _blacklist variable to include '__class__', '__globals__', 'hasattr' as 3 seperate strings and not '__class____globals__hasattr' as 1 combined string

Fixed the _blacklist variable

---

UM/PackageManager.py

Added some logic to obtain the **to be removed** and **to be installed** packages.
Which simplifies the logic in the Cura Marketplace plugin. See PR Ultimaker/Cura#10732

Cura 8558 get removed and to install packages

---

UM/View/SelectionPass.py

PyQt Pixel expects integer coordinates as parameters.
This fixes the crash on cura when using the
"Select face to align to the build plate" tool

Round coordinates on getFaceIdAtPosition

---

UM/Qt/Bindings/ViewModel.py

(for plugins with 2 views or more)
If a view has a _name, its ID is not PluginName but rather PluginName_ViewName. This is necessary to give unique IDs to each view in a plugin that has multiple views. However, it breaks this line:
```
view_meta_data = PluginRegistry.getInstance().getMetaData(view_id).get("view", {})
```
because it tries to look for a plugin called PluginName_ViewName.
More info in [Cura forums thread](https://community.ultimaker.com/topic/38259-plugin-development-hide-a-new-view-from-the-view-selector-in-preview-stage/?tab=comments#comment-297251) & issue #744.

Repaired Views dropdown in Preview stage

---

UM/Version.py
tests/TestVersion.py

The postfix logic was pretty much broken. I don't know why this was originally added.
The ticket it refers to is an embedded ticket that doesn't have anything to do with this and was
created well after this commit.
CURA-8696
https://github.com/Ultimaker/Cura/pull/10977

Fix postfixes in the versioning

---

UM/PluginRegistry.py

This should warn the user that a backed up plugin has been corrupted and should be reinstalled
Contributes to: CURA-8666

Shows a remove plugin message if the central storage location is missing

---

UM/Signal.py

This makes the signals significantly faster.
The results were most visible in creation of the container trees (where a lot of signals are connected). This made it ~5x as fast to populate the container tree.

Use a direct copy instead of cleanup for signal connect

---

UM/Settings/ContainerQuery.py

By adding the values of the medatada dict to a list, a complete copy of the list is made. This isn't actually needed, since we just want to filter results (wich are then copied to a list). As unneeded copies tend to be on the expensive side, this makes profile loading a lot faster

Prevent unneeded copy in container query

---

plugins/Tools/RotateTool/RotateToolHandle.py
plugins/Tools/ScaleTool/ScaleToolHandle.py
plugins/Tools/TranslateTool/TranslateToolHandle.py
resources/shaders/composite.shader
resources/shaders/toolhandle.shader

This PR Improve the visualization of the widgets used to translate, rotate, mirror and scale. 
- minor adjustments were made to the shape of the 3d arrows for translate and rotate
- the line thickness of the widget was decreased
- and to keep the colours of the axis aligned with the origin widget color the behaviour of the over was changed: Instead of decreasing the brightness on hover, we now increase the brightness.
See also https://github.com/Ultimaker/Cura/pull/11486

Azis and transform widget visualisation improvements

---

UM/Qt/qml/UM/Dialog.qml

Fixed by removing the `Qt.Dialog` flag. According to the [documentation](https://doc.qt.io/qt-5/qt.html#WindowType-enum) this flag achieves two things
- block events to the main window
- Only present the close button in the dialog title bar, and leave out the minimize, full screen buttons
When removing the `Qt.Dialog` flag the behavior was still as expected. Was only able to test this on Ubuntu.
CURA-8988

Make dialogs draggable

---

UM/Qt/qml/UM/Enums.qml
UM/Qt/qml/UM/ToolTip.qml
UM/Qt/qml/UM/ToolbarButton.qml
UM/Qt/qml/UM/qmldir
plugins/Tools/RotateTool/RotateTool.qml
plugins/Tools/ScaleTool/ScaleTool.qml

Rotate Tool & Scale tool image buttons swapped out for new style _ToolbarButton_ that is used in _Per Model Settings_
Moved Tooltip.qml and ToolbarButton.qml into Uranium so that the plugins/Tools can access these elements.
CURA-8943

[CURA-8943] Update Tool Panel Icons style

---

plugins/LocalFileOutputDevice/LocalFileOutputDevice.py

Setting this env: `export QT_QPA_PLATFORMTHEME=xdgdesktopportal`
should fix the File dialogs not opening up on various Linux systems,
or opening up very slowely. This should use the native dialog on,
every system. Our previous implementation was depended on a Filedialog
which used a DirectoryList qml object which wasn't part of the PyQt6
binaries.
Contributes to CURA-9123

Using xdgdektopportal for File dialogs on Windows

---

UM/Qt/Bindings/MainWindow.py

This fixes a TODO that was still in the code there.
In Qt6, the WindowState is a proper enum instead of an integer field in the Qt class. The setWindowState function expects that enum, not an integer. We were storing the integer in Cura 4, so that integer should be converted into the enum before calling setWindowState.
Additionally we were also converting the WindowState enum to a string when serialising it for the preferences class. This causes a problem with the version upgrade because the data in cura.cfg would need to change.
This change here fixes both. It makes the cura.cfg file store the integer as before so no version upgrade will be necessary for this. And it converts it properly to an enum for the setWindowState function.
Fixes issue CURA-9171.

Fix restoring window state upon restart

---

UM/View/GL/OpenGLContext.py

gl_window is used to detect the opengl version on some MacOs versions. This seems to have been unassigned automagically in QT5. With QT6 it was staying open in the background.
The fix here is to assign it to null to remove it from memory.
CURA-9145

CURA-9145 Small Black window appears on macOS

---

resources/shaders/toolhandle.shader

This PR fixes the rendering of ToolHandles when in "compatibility mode" (OpenGL 2). In legacy GLSL, `gl_FragColor` is a fixed keyword.
Fixes https://github.com/Ultimaker/Cura/issues/11882

Fix ToolHandle rendering in compatibility mode

---

UM/Qt/QtApplication.py

This PR changes how applications force using the "fusion" style. Without this, Windows mixes in a "native" style which adds strange overlays on hover which negatively affect readability and break consistency across platforms.
The previous QApplication.setStyle() after initialising the QApplication class no longer seems to work in Qt6 (if it ever worked).

[5.0b1] Fix using "Fusion" as the base style for applications

---

UM/Qt/qml/UM/TooltipArea.qml

This PR fixes the TooltipArea control, which is no longer working because it was using a private QtQuick Controls 1 element. The PR wraps the UM.Tooltip, so tooltips are now styled like the rest of the app. The tooltip does not have an arrow pointing towards the TooltipArea, so we are more free to place oversize tooltips in such a way that they don't pop up in a way that they need to immediately close because they obscure the TooltipArea.

[5.0b1] Fix TooltipArea

---

UM/Version.py
plugins/UpdateChecker/UpdateChecker.py

Retrieved beta version would always be > local beta version.
Since we can't store the postfix (only up to 'revision' level) and major.minor.revision is loaded as 3 intergers from (online) latest.json -- the latest BETA version would always be (stoed online and) retrieved as a.b.c (withouth postfix info), but compared against the local a.b.c-beta+whatever (so, with postfix). The algorithm would then quite correctly deduce that a.b.c-beta+whatever was in fact a 'smaller' version than a.b.c (no postfix). Which then would lead to a message that a new beta was avialable _even if the user was already runnng said beta_.
This fixes that, but the underlying issue (not providing a postfix version) still remains. Problems this could cause are when we want to release and announce a second beta, …

[CURA-8856] Don't spam the user already running the beta with a notification for said beta.

---

UM/Qt/qml/UM/CheckBox.qml
UM/Qt/qml/UM/ImageButton.qml
UM/Qt/qml/UM/Label.qml
UM/Qt/qml/UM/MessageStack.qml
UM/Qt/qml/UM/ToolTip.qml

Fonts were looking a bit to thick on when using `Text.NativeRendering`, so using `Text.QtRendering` instead. After this the font weight looks identical to figma (as far as I can see).
In this commit I also changed all `Label`'s to `UM.Label`'s and removed default properties where I could.
CURA-9154

Render labels using `Text.QtRendering` on OSX

---

UM/Application.py

This was recently added. However it appears that we have the same path multiple times in the resources, leading to the resources being found twice. This would normally get removed by virtue of being a set, but not this time since it's a different way of writing the same path.
For the themes, it finds the following paths (in my unpacked directory): `{'/home/trin/tempy/cura5/UM/../share/uranium/resources/themes', '/home/trin/tempy/cura5/cura/../share/cura/resources/themes', '/home/trin/tempy/cura5/share/cura/resources/themes', '/home/trin/.local/share/cura/5.0/themes', '/home/trin/tempy/cura5/share/uranium/resources/themes'}` For both Cura and Uranium, this points to /home/trin/tempy/cura5/curanium/resources/themes twice. So let's remove this one.
Contributes to issue CURA-9147.

Remove extra resource path from Python file

---

UM/Qt/qml/UM/TooltipArea.qml

Problem was that the mouse events were not properly propagated to the underlying mouse area. Fixed by placing the MouseArea on top of the content (instead of under) and allowing the mouse events to propagate through the mouse area. This way we don't have to propagate the mouse event for each individual component that could be located within the ToolTipArea.
Also removed some logic where the properties of the Mouse area were exposed. However this was only used in one instance (as far as I could find) and in my opinion this was abusing the intended use of the ToolTipArea component. This last issue is simply fixed by adding an additional mouse area.
CURA-9219

Fix for tooltip

---

UM/Preferences.py
UM/Qt/Bindings/Theme.py
UM/Qt/QtApplication.py

This was a bit more tricky then it at first seemed, since the information whether this is a 'secure version' comes from the user-application and is not known in the Uranium library. This is not normally such a point, but both the theme and the preferences objects are loaded _very_ early in the process, and that information needs to be injected before then. (Well, in the case of the Theme object it's less important, since in the implementation chosen that is now security wise at least only in charge of whether or not to even show the theme as selectable in the interface, so that it only needs to be aware of the 'security' status any time before the user can see a preference screen, but not necessarily earlier.)
See also frontend PR.

[SEC-255] [CURA-8966] In secure version: disable loading themes from unbundled folders.

---

UM/Preferences.py
UM/Qt/Bindings/Theme.py
UM/Qt/QtApplication.py

5.0 version of: https://github.com/Ultimaker/Uranium/pull/822
So we can merge to the main branch later without (much?) conflicts should that be needed.
Of course this also has a corresponding front-end PR.

In secure version: disable loading themes from unbundled folders.

---

UM/Preferences.py
UM/Qt/QtApplication.py

Seems like we _may_ start the socket for listening for the engine first, depending on threading, which doesn't open the engine itself, but does mess with the order of the preference reading. Also rename settings -> preferences.
SEC-257 | CURA-8968

[CURA-8968] Also check afterwards.

---

UM/Settings/InstanceContainer.py
UM/VersionUpgrade.py
UM/VersionUpgradeManager.py

Invalid string escapes print ugly DeprecationWarnings, but might result
in SyntaxErrors somewhen in the future. I'd rather fix them, so my Log
files aren't cluttered with pointless warnings.
Currently starting Cura will look like that for me:
```
/usr/lib/python3.10/site-packages/UM/PluginRegistry.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
import imp
/usr/lib/python3.10/site-packages/UM/Settings/InstanceContainer.py:53: DeprecationWarning: invalid escape sequence '\d'
version_regex = re.compile("\nversion ?= ?(\d+)")
/usr/lib/python3.10/site-packages/UM/Settings/InstanceContainer.py:55: DeprecationWarning: invalid escape sequence '\w'
type_regex = …
```

Fix invalid string escapes

---

plugins/Tools/CameraTool/CameraTool.py

Zoom toward mouse always referenced the mouse position as half the actual position. Mainly due to calculations based on the viewport centre rather than the dimensions and native mouse positions. This patch fixes it by not referencing the centre of the viewport, but to the mouse position directly.

Fix "Zoom Toward Mouse Direction" #6775

---

requirements.txt

Seems networkx itself is low on dependencies itself. It does require some optional ones for e.g. it's linalg sub-package, but those are numpy and scipy, which we already have.

[CURA-9535] Some trimesh operations require networkx

---

UM/Scene/Scene.py

Solved simply adding one additional check before showing the popup where we look at the “last modified” timestamp of the model. If this timestamp is too far in the past we don’t show the popup. This difference in time was around ~0.5ms when testing, but set to 10000ms (10s) just to be certain.
Fixes: https://github.com/Ultimaker/Cura/issues/12322
CURA-9417

Prevent "files changed" popup when file did not change

---

plugins/Tools/RotateTool/RotateTool.py

Added decimals capability to the RotateToolHandle Hint without modifing the integer displaying of snap rotation.
I think this change can improve the user experience when using rotation without snap, which with just displaying the unit could cause some issues (see https://github.com/Ultimaker/Cura/issues/12625).
Can it be integrated within the next version of Cura?

[Cura 12625] Added decimals capability to the RotateToolHandle Hint

---

.github/workflows/unit-test.yml
conanfile.py

Added a build step which uses the Conan package gettext as a tool_requires to convert the po files to mo files and store these in the resources folder
When on Windows the msys2 recipe is used to ensure that we have a bash environment to run gnu gettext
Creating the mo files as part of the conan package will ensures that we no longer need to store them in the cura-binary-data and generate them manually. This should result in less risk of human error during the release cycle
See also:
- https://github.com/Ultimaker/Cura/pull/13596
- https://github.com/Ultimaker/cura-binary-data/pull/26

Build mo translation files when creating conan package

---

plugins/LocalFileOutputDevice/LocalFileOutputDevice.py

This pull request splits the `requestWrite` method in the `LocalFileOutputDevice` plugin to allow intercepting of writes for logging purposes. The specifics of this are covered in Ultimaker/Cura#10917.
Example usage for The Construct @ RIT that uses a patch to get this change: https://github.com/TheConstructRIT/Construct-Cura-Plugins/blob/master/ConstructPaymentWindow/__init__.py

Split requestWrite to Allow Intercepting Writes.

---

resources/bundled_packages/uranium.json

Changes the plugin  display name: from `Ultimaker B.V.` to `UltiMaker`
Contributes to CURA-9808

Use UltiMaker for display name plugins

---

UM/Scene/Platform.py

Re: https://community.ultimaker.com/topic/34232-how-do-i-add-my-printers-logo-to-the-cura-bed/?do=findComment&comment=293900
The x, y, z offset is read in from the user .cfg file as a string, but the code expects a list of floats. The check for 3 items always fails with sensible data as it returns the number of characters in the string.
I am checking if the instance of offset is a string because I believe this offset is also provided by .json printer definition files as the correct data type and we don't want to break that.

Fix longstanding bug with 'platform_offset'

---

UM/Settings/SettingFunction.py

Previously, if anything was wrong, only the (stacktrace of the) error itself, so _within_ the setting-function, would be printed. Now we also get where this evaluation was called from.
done as part of CURA-9859

Print stacktrace of current location.

---

UM/Settings/AdditionalSettingDefinitionAppender.py
UM/Settings/ContainerRegistry.py
UM/Settings/DefinitionContainer.py
tests/Settings/TestAppendAdditionalSettings.py
tests/Settings/additional_settings/append_extra_settings.def.json
tests/Settings/definitions/append_extra_settings.def.json
tests/TestTrust.py

Plugins should now be able to add settings. (But not append enum-values to existing ones, that's another ticket.)
- (De)serialization works, including load/save.
- Keys are tagged/'namespaced' with provider type (just a plugin for now), unique id, version.
- Will be sent to engine (except you have to demangle the tagged/namespaced name a bit).
- Setting-formulas work (except for taking values of another plugin).
- Can add to an existing category, or create a new one.
See (now) also the accompanying front-end PR here: https://github.com/Ultimaker/Cura/pull/16305

[CURA-10722] Add 'additional settings providers' (Engine Plugins)

---

UM/PluginRegistry.py

This will actually re-enable plugins that are marked as required. It should never have bene possible to disable required plugins in the first place. 
Goes with https://github.com/Ultimaker/Cura/pull/16304

Fix required plugins

---

UM/Qt/qml/UM/MessageStack.qml
UM/Qt/qml/UM/ScrollableTextArea.qml
UM/Qt/qml/UM/qmldir

Long messages are now scrollable. I reused the existing ScrollableTextArea, which has moved from Cura to Uranium, and changes the behavior of the user interactions :
* :+1: The text can now be selected, so the user may easily Google it in case of an error 
* :+1: The scrollbar only appears if the text is too high (fixed max size, to be discussed)
* :-1: When scrolling quickly, the last wheels moves actually zoom in/out on the 3d view
Maybe we should also consider making the dialog box a bit larger ?

Cura 9374 make long messages scrollable

---

plugins/LocalFileOutputDevice/LocalFileOutputDevice.py

As for removable drives, we now delete the GCode file if it could not be fully exported due to hard drive being full.
The method LocalFileOutputDevice._onWriteJobFinished is 95% similar to RemovableDriveOutputDevice._onFinished, so maybe we should merge them somehow ?

Remove partially exported file on hard drive

---

UM/Math/Polygon.py

Add an extra check to ensure that calling `scale()` on an empty `Polygon` will not generate an exception.
CURA-10004

Fix numpy exception with polygon scaling

---

UM/Settings/ContainerRegistry.py

If the name was missing it would cause Cura to crash. If the type was missing it wouldn't crash, but it would silently fail to load the model which is also not good. With this change, in both cases it will add a warning to the log.
Contributes to issue CURA-3Z4.
This PR requires https://github.com/Ultimaker/Cura/pull/12473 to be merged as well. Otherwise the Cura tests will fail because of this change.

Don't allow containers without type and name in container registry

---

UM/Qt/qml/UM/Menu.qml
UM/Qt/qml/UM/MenuItem.qml

* The first mentioned QML warning has been fixed already with commit 1f67452346a5eda0c37c71a746d4a5cd44d33563
* Fixed two other QML binding loop warnings.
* The one in `Menu.qml` implies that the width of the menu will not automatically change if any of the menu item changes. It will be updated only when the menu is opened again. In practice, this does not happen because it would be very user-unfriendly to have a menu that changes its width while the mouse cursor is over it.

[CURA-11102] qml warnings

---

UM/Qt/Bindings/ActiveToolProxy.py

Commit https://github.com/Ultimaker/Uranium/commit/4f328198c4cca4b3f0f7af82f7b81faa5e8479a1 fixes exceptions where an empty string would be set to a floating-point property value. However, in some cases it prevents the values being intentionally set to an empty string (for properties that are actual string). This fix introduces an other way of handling this issue.
CURA-11215

Better handling of inconsistent property values

---

UM/Scene/Scene.py

When a 3MF file that has multiple models inside is loaded, Cura will alert if the file has been modified and asks if the user wants to reload id. When that happen, all objects from that file where being replaced by the first model in the file.
Another minor issue was that when reloading, Cura would read the same file multiple times, one for each model.
! Important: This PR Requires https://github.com/Ultimaker/Cura/pull/16610
- Confirmed other filetypes where not affected by the refactor:
- Opened a OBJ file and reloaded.
- Opened STL file and reloaded.
- Opened gcode file, and reloaded.
- Loaded a 3MF file with multiple models into Cura, verified the name of the models in the app are the model name in the file.
- Updated the 3MF file changing the mesh for the models but keeping the …

Refactor object reload to handle 3mf files

---

UM/Qt/Bindings/ActiveToolProxy.py
UM/Qt/Bindings/ApplicationProxy.py
UM/Qt/Bindings/Bindings.py
UM/Qt/Bindings/ControllerProxy.py
UM/Qt/Bindings/OperationStackProxy.py
UM/Qt/QtApplication.py
plugins/Tools/RotateTool/RotateTool.qml
plugins/Tools/ScaleTool/ScaleTool.qml
plugins/Tools/TranslateTool/TranslateTool.qml

CURA-7812
Delete and refactor a number of singletons in QML to clean up the code. Document the refactor decisions made in the SDK documentation. 
Deleted: (Deprecated)
QualityManagementModel
MaterialManagementModel
QualityProfilesDropDownMenuModel 
SimpleModeSettingsManager
MachineActionManager
UM.Application 
CustomQualityProfilesDropDownMenuModel
Merged: (also deprecated)
WorkspaceFileHandler (merged with meshfile )
OperationStack (merge with actions)
ActiveTool (merge with Controller)

CURA-7812-decrease-Qml-singletons

---

UM/Application.py

See Cura PR: https://github.com/Ultimaker/Cura/pull/18188
CURA-11483

Fix mac builds

---

UM/View/SelectionPass.py
plugins/Tools/RotateTool/RotateTool.py
plugins/Tools/SelectionTool/SelectionTool.py
resources/shaders/select_face.shader
tests/Scene/TestSelection.py

It wouldn't even let you select a face if the selected node was a group or a merged mesh.
Should fix https://github.com/Ultimaker/Cura/issues/14237

[CURA-10149] make 'Lay Flat By Face' work for groups & merges

---

UM/Qt/qml/UM/CheckBox.qml

Fix tooltip in the checkbox component, previously we were using Qt's "native" tooltop. Swapped it for the UM.ToolTip for consistency with the whole application.
CURA-11697

Fix checkbox tooltip

---

UM/Settings/ContainerStack.py
UM/Settings/InstanceContainer.py

Instead of getting all the settings and checking for their state, run only once through all the containers and gather only the keys having a User state.
Comes with https://github.com/Ultimaker/Cura/pull/18592
CURA-11475

Cura 11475 low performance multiple nozzles

---

UM/Qt/ListModel.py
UM/Settings/Models/DefinitionContainersModel.py

this condition fails and creates a crash when changed_row_count ==0
CURA-11003

Implement printer search feature in local printer selection

---

UM/Job.py

Following the removal of the get/setMessage methods in the Job class, the StartSliceJob has not been updated and still used them. We now use a specific variable for storing the disabled extruders and properly display them.
CURA-11904
Associated PR https://github.com/Ultimaker/Cura/pull/19076

CURA-11904 Fix crash when slicing with first extruder disabled

---

UM/Settings/DefinitionContainer.py
UM/Settings/SettingDefinition.py

This is a workaround for a case where it is not possible to know in advance what settings a setting depends on, e.g. if the function is overridden by a material profile. This way we can explicitely specify an extra list of dependencies.

CURA-12009 add setting depends on

---

plugins/Tools/TranslateTool/TranslateTool.py

Add a direction variable that changes to -1 if the y axis if flipped in the preferences.
This will put the values shown in the UI in line with the direction of the tool handle flip (Y+ is in direction that the toolhandle points to)
https://github.com/Ultimaker/Cura/pull/20006

TranslateTool.py update setter and getter to allow for Y axis flip to show expected values in UI for Y

---

UM/Math/Quaternion.py
plugins/Tools/RotateTool/RotateTool.py
plugins/Tools/RotateTool/RotateTool.qml
plugins/Tools/ScaleTool/ScaleTool.qml

Add rotation by input fields
- Fields only active when snap rotation is disabled
- Fields take user input, rotate the model and return to value 0
- Getting model rotation or storing the rotation values lead to unexpected behavior (read leave Quaternions alone)
- Includes the snap rotation PR (https://github.com/Ultimaker/Uranium/pull/979)
- Adds setter and getter for RX,RY,RZ (rotations in each axis)
- Applies the rotations for single or multiple model(s)
Rotate by input
Snap angle update
Based on the idea of GregValiant

Rotation by input & snap angle input

---

conandata.yml

Add Qt as an extra dependency for which we want to display the license
CURA-12400
Requires https://github.com/Ultimaker/Cura/pull/20291

CURA-12400 improve open source referencing

---

UM/OutputDevice/ProjectOutputDevice.py

CURA-12403
:warning: This is technically an API change, but we already made the annoucement for the API change. Should we still update the wiki silently ?
Comes with https://github.com/Ultimaker/Cura/pull/20377

CURA-12403 Fix wrongly switching project name

---

UM/View/GL/OpenGL.py
UM/View/RenderBatch.py

This could happen when an other Cura window was open, apparently the QML rendering then creates a different OpenGL context and we need to switch back to our own context before starting to draw
CURA-12309
Fixes https://github.com/Ultimaker/Cura/issues/19904

CURA-12309 hard crash when modifying a post processing setting value with auto slice

---

UM/Mesh/MeshWriter.py
plugins/FileHandlers/OBJWriter/OBJWriter.py
plugins/FileHandlers/STLWriter/STLWriter.py
plugins/LocalFileOutputDevice/LocalFileOutputDevice.py

Updates the mesh writers to handle the `mime_type` argument
Comes with https://github.com/Ultimaker/Cura/pull/20518
CURA-12099

CURA-12099 export and import to bambu 3mf

---

UM/Mesh/MeshWriter.py
plugins/FileHandlers/OBJWriter/OBJWriter.py
plugins/FileHandlers/STLWriter/STLWriter.py
plugins/LocalFileOutputDevice/LocalFileOutputDevice.py

Updates the mesh writers to handle the mime_type argument
Comes with https://github.com/Ultimaker/Cura/pull/20563
CURA-12099
CURA-12057

CURA-12074 introduce bambu printers

---

UM/Resources.py

When using an alpha version, create a config folder specific to this version, so that non compatible configs won't mix
CURA-12408
This removes the check for a version called `master`, `main` or `dev`, since we do not use that anymore. The Cura version is handled through Conan and there is no situation where this could happen.

CURA-12408 separate alpha config folders

---

UM/Qt/qml/UM/Validators/FloatValidator.qml

CURA-12723
This makes sense as the numbers are already rounded to 4 decimal digits. More than 4 gives a weird behavior.

CURA-12723 fix the validator for text fields
