- UM/Mesh/ReadMeshJob.py
- UM/Qt/Bindings/Bindings.py
- UM/Qt/Bindings/PointingRectangle.py
- UM/Qt/Bindings/Theme.py
- UM/Qt/Bindings/ToolModel.py
- UM/Qt/qml/UM/MessageStack.qml
- UM/Qt/qml/UM/Settings/SettingCheckBox.qml
- UM/Qt/qml/UM/Settings/SettingComboBox.qml
- UM/Qt/qml/UM/Settings/SettingItem.qml
- UM/Qt/qml/UM/Settings/SettingItemStyle.qml
- UM/Qt/qml/UM/Settings/SettingTextField.qml
- UM/Qt/qml/UM/Settings/SettingView.qml
- UM/Qt/qml/UM/Settings/SidebarCategoryHeader.qml
- plugins/Tools/MirrorTool/__init__.py
- plugins/Tools/RotateTool/RotateTool.qml
- plugins/Tools/RotateTool/__init__.py
- plugins/Tools/ScaleTool/ScaleTool.qml
- plugins/Tools/ScaleTool/__init__.py
See Ultimaker/Cura#562
(resubmitted PR #77 against 2.1 branch)
> Design rework for 2.1 release

- UM/Qt/Bindings/ProfilesModel.py
- UM/Qt/qml/UM/Preferences/ProfilesPage.qml
- UM/Settings/MachineManager.py
- UM/Settings/ProfileReader.py
- UM/Settings/ProfileWriter.py
This feature introduces plug-in readers and writers.
It also creates two new types of plug-ins: Profile Reader and Profile Writer, which is desired for a new feature in Cura to write and load settings in g-code.
A similar pull request is made for Cura. They should be tested together.
> Write and Read Profile in plug-ins

- UM/Qt/Bindings/ProfilesModel.py
- UM/Qt/Bindings/ViewModel.py
- UM/Qt/qml/UM/MessageStack.qml
- UM/Qt/qml/UM/Preferences/MachinesPage.qml
- UM/Qt/qml/UM/Preferences/ManagementPage.qml
- UM/Qt/qml/UM/Preferences/PreferencesDialog.qml
- UM/Qt/qml/UM/Preferences/ProfilesPage.qml
- UM/Qt/qml/UM/Settings/SettingItem.qml
- UM/Qt/qml/UM/Settings/SidebarCategoryHeader.qml
- plugins/Tools/RotateTool/RotateTool.qml
- plugins/Tools/ScaleTool/ScaleTool.qml
Followup for https://github.com/Ultimaker/Uranium/pull/80
Fixes for comments on CURA-348
See also https://github.com/Ultimaker/Cura/pull/571
> Updated Design rework for 2.1 release

- UM/Qt/Bindings/MeshFileHandlerProxy.py
Fixes CURA-567
See http://stackoverflow.com/questions/26867595/qml-filedialog-namefilters-case-sensitive-on-linux
> Add uppercase extensions to File Open dialog

- resources/i18n/de/uranium.po
Needed for PR: https://github.com/Ultimaker/Cura/pull/629
> i18n: de: Another set of translation improvements

- UM/Math/Matrix.py
- UM/Math/Vector.py
- UM/Operations/MirrorOperation.py
- UM/Operations/ScaleOperation.py
- UM/Scene/SceneNode.py
- plugins/Tools/MirrorTool/MirrorTool.py
- plugins/Tools/ScaleTool/ScaleTool.py
- tests/Scene/TestSceneNode.py
> Scale rework

- UM/Qt/Bindings/ProfilesModel.py
- UM/Qt/qml/UM/Preferences/ProfilesPage.qml
> Bugfix 667

- UM/Decorators.py
- UM/Logger.py
- UM/Qt/Bindings/ProfilesModel.py
- UM/Qt/Bindings/SettingCategoriesModel.py
- UM/Qt/Bindings/SettingsFromCategoryModel.py
- UM/Qt/Bindings/Theme.py
- UM/Qt/qml/UM/MessageStack.qml
- UM/Qt/qml/UM/Preferences/MachinesPage.qml
- UM/Qt/qml/UM/Preferences/ManagementPage.qml
- UM/Qt/qml/UM/Preferences/PluginsPage.qml
- UM/Qt/qml/UM/Preferences/PreferencesDialog.qml
- UM/Qt/qml/UM/Preferences/PreferencesToolTip.qml
- UM/Qt/qml/UM/Preferences/ProfilesPage.qml
- UM/Qt/qml/UM/Preferences/SettingVisibilityPage.qml
- UM/Qt/qml/UM/Settings/SettingCheckBox.qml
- UM/Qt/qml/UM/Settings/SettingComboBox.qml
- UM/Qt/qml/UM/Settings/SettingItem.qml
- UM/Qt/qml/UM/Settings/SettingTextField.qml
- UM/Qt/qml/UM/Settings/SettingUnknown.qml
- UM/Qt/qml/UM/Settings/SettingView.qml
- UM/Qt/qml/UM/Settings/SidebarCategoryHeader.qml
- UM/Qt/qml/UM/SimpleButton.qml
- UM/Qt/qml/UM/Wizard.qml
- UM/Qt/qml/UM/qmldir
- UM/Scene/Platform.py
- UM/Settings/Profile.py
- plugins/Tools/RotateTool/RotateTool.qml
- plugins/Tools/ScaleTool/ScaleTool.qml
- plugins/Tools/TranslateTool/__init__.py
- resources/i18n/nl/uranium.po
This makes profile switiching, variant switching and machine switching react in <500ms, with one minor visual regression: Setting items will pop-in relatively randomly when switching, instead of directly appearing. In my opinion, it is a trade-off we can live with.
Fixes CURA-472
> Performance fixes

- UM/Qt/qml/UM/Settings/SettingView.qml
This should fix https://github.com/Ultimaker/Uranium/issues/121 .
Please test before merging.
> [2.1] Hotfix: Moving formating outside of i18nc

- docs/translations.md
This shows the usage of the generated helper targets.
There is more to add, but this should be fine at the moment.
> [master] i18n: Update instructions for new helper targets

- UM/PluginRegistry.py
- UM/Qt/qml/UM/Wizard.qml
> Machine actions

- UM/Mesh/MeshData.py
- plugins/FileHandlers/STLReader/STLReader.py
Improve speed of .stl loading by ~20x. 
CURA-1749
> Feature stl speed improvement

- UM/Operations/OperationStack.py
- plugins/Tools/RotateTool/RotateTool.py
- plugins/Tools/ScaleTool/ScaleTool.py
- plugins/Tools/TranslateTool/TranslateTool.py
> [CURA-1502] Better implementation of Undo bug.

- UM/Dictionary.py
- UM/Qt/Bindings/Bindings.py
- UM/Qt/QtApplication.py
- UM/Qt/qml/UM/Preferences/ManagementPage.qml
- UM/Settings/ContainerRegistry.py
- UM/Settings/InstanceContainer.py
- UM/Settings/Models/ContainerPropertyProvider.py
- UM/Settings/Models/InstanceContainersModel.py
- UM/Settings/Models/__init__.py
This includes a bunch of changes needed to make it possible to edit materials.
> Support work for Material Editing

- UM/Backend/Backend.py
This is useful to limit the size of the log depending on our needs.
Contributes to CURA-1775
> Backend: Adding possibility to cut a special count of lines

- UM/Mesh/MeshBuilder.py
- UM/Mesh/MeshData.py
Adds convenience functions to MeshData used in commits for Cura and CuraEngine to speed-up layerview
> Added convenience functions to better build meshes

- plugins/UpdateChecker/UpdateChecker.py
Does the same like in SliceInfo in Cura.
Additionally I replaced the current usage of threading with UM.Job.
Contributes to CURA-1923
> [CURA-1923] UpdateChecker: Using jobs for checking and cleanups

- plugins/Tools/MirrorTool/__init__.py
- plugins/Tools/RotateTool/__init__.py
- plugins/Tools/ScaleTool/__init__.py
- plugins/Tools/TranslateTool/__init__.py
A number of issues were found where the UI uses terms that do not comply to the terms set in the "Ultimaker dictionary".
CURA-2053
> Update UI texts to be compliant to Ultimaker dictionary

- UM/Mesh/ReadMeshJob.py
Brings the basic functionality needed for the JIRA issue.
(Additionally just renamed some variables and sorted some.)
> CURA-2050: Ignore scaling less then 1.25 times bigger

- CMakeLists.txt
- cmake/UraniumTranslationTools.cmake
Moves all macros and also the if clause, which looks for Gettext.
> [CURA-1696] Move translation targets to a separate module

- UM/Qt/Duration.py
- resources/i18n/pl/uranium.po
- resources/i18n/uranium.pot
Also changed formatting of long representation of print time – not it uses plural forms. I'm not sure if it's the best way to do it. Feel free to change it. Unfortunately it required updating `pot` file, so it's a little bit messy.
> Added Polish translation

- UM/PluginRegistry.py
No more left to say.. Just adds this simple function.
> PluginRegistry: Add isActivePlugin function

- UM/Settings/ContainerRegistry.py
- UM/Settings/ContainerStack.py
- UM/VersionUpgradeManager.py
Part of "CURA-2953 Version upgrade 2.3 to 2.4"
> CURA-2953 Version upgrade 2.3 to 2.4

- scripts/extract-messages
This reverts commit b8119f3cb047b467024dfa179a1365a3413c60b8.
> Revert "i18n: Remove creation of en translations"

- resources/i18n/en/uranium.po
- resources/i18n/hu/uranium.po
- resources/i18n/uranium.pot
In order to translate Cura into Hungarian I would try to translate Cura incl. Uranium using Launchpad.net's translation interface.
The empty translation file - uranium.po - is needed, so Launchpad can import the file into its system.
However, @femmuhely has to create a Launchpad.net account first.
* https://github.com/Ultimaker/Cura/pull/1230#issuecomment-267035638
> [master] i18n: Updating translation files and add empty Hungarian translation

- resources/i18n/ru/uranium.po
> Added Russian translation.

- UM/FlameProfiler.py
- UM/Qt/Bindings/ContainerProxy.py
- UM/Qt/Bindings/ExtensionModel.py
- UM/Qt/Bindings/MeshListModel.py
- UM/Qt/Bindings/ResourcesProxy.py
- UM/Qt/Bindings/Theme.py
- UM/Qt/Bindings/VisibleMessagesModel.py
- UM/Qt/Bindings/i18nCatalogProxy.py
- UM/Qt/Duration.py
- UM/Settings/ContainerRegistry.py
- UM/Settings/Models/ContainerPropertyProvider.py
- UM/Settings/Models/SettingDefinitionsModel.py
- UM/Settings/Models/SettingPropertyProvider.py
- UM/Signal.py
The Uranium support needed for the Big Flame Graph profiler. It currently always inserts the shims to add profiling, there is no option to turn that on/off at start up.
The plugin itself is: https://github.com/sedwards2009/cura-big-flame-graph
> Big flame graph profiler support

- Jenkinsfile
- UM/Settings/ContainerRegistry.py
- pylint.cfg
- tests/Math/TestPolygon.py
- tests/MimeTypes/TestMimeTypes.py
- tests/Settings/TestContainerRegistry.py
- tests/Settings/TestContainerStack.py
- tests/Settings/TestInstanceContainer.py
- tests/Settings/TestRoundtripping.py
- tests/Settings/TestSettingFunction.py
- tests/Settings/conftest.py
- tests/VersionUpgrade/TestVersionUpgradeManager.py
This introduces a Jenkinsfile which is a script describing the process to build and test Uranium on the new Ultimaker CI system. In addition, it fixes a number of unit tests and marks others to be skipped.
> Jenkins ci test

- UM/Qt/GL/QtOpenGL.py
> Revert "CURA-3191: QtOpenGL: Adding workaround for undecodable string"

- resources/i18n/ptbr/uranium.po
As per directions from Cura issue 676, I created this translation file alongside the translation files for Cura to have english strings translated to brazilian portuguese strings using gettext.
> Added translation files for brazilian portuguese

- UM/Qt/Bindings/Bindings.py
- UM/Qt/Bindings/OpenGLContextProxy.py
- UM/Qt/QtApplication.py
- UM/Qt/QtRenderer.py
- UM/Qt/qml/UM/RecolorImage.qml
- UM/View/DefaultPass.py
- UM/View/GL/OpenGL.py
- UM/View/GL/OpenGLContext.py
- UM/View/GL/ShaderProgram.py
- UM/View/RenderBatch.py
- UM/View/SelectionPass.py
- resources/shaders/color.shader
- resources/shaders/composite.shader
- resources/shaders/default.shader
- resources/shaders/platform.shader
- resources/shaders/selection.shader
- resources/shaders/toolhandle.shader
- Added OpenGLContext and OpenGLContextProxy
- Added 41core shaders.
- Use 41core shader if supported, else use compatibility shader.
- VertexArrayObjects are used if supported
- Added context compatibility check, for 4.1 core and also for 2.0
- Try to set 4.1 core profile, if failed, take 2.0, if failed error
Together with
https://github.com/Ultimaker/Cura/pull/1405
> Opengl41core - on top of layer_view3_cleanup

- UM/Application.py
> Check hide message id before processing

- UM/Application.py
- UM/i18n.py
> CURA-3584: Fix i18n switching language doesn't work

- UM/PluginRegistry.py
- UM/Qt/Bindings/PluginsModel.py
- UM/Qt/qml/UM/Preferences/PluginsPage.qml
This is useful eg when users don't want to use USB printing, and they don't want to the USB printing plugin to reset their arduinos when Cura starts.
NB: The application needs to be restarted for changes to have effect.
> Allow the user to disable/enable plugins

- UM/Resources.py
> Store cache directory in LOCAL on Windows

- resources/i18n/ptbr/uranium.po
Updated pt-br translations for Cura 2.5.
> Updated pt-br translations for Cura 2.5

- UM/Resources.py
- UM/VersionUpgradeManager.py
- tests/TestResources.py
In combination with https://github.com/Ultimaker/Cura/pull/1672
> CURA-3529 Copy the latest cura dir (if present) for upgrade

- UM/Decorators.py
- UM/Settings/ContainerRegistry.py
- UM/Settings/ContainerStack.py
- UM/Settings/DefinitionContainer.py
- UM/Settings/InstanceContainer.py
- UM/Settings/Interfaces.py
- UM/VersionUpgradeManager.py
- tests/TestDecorators.py
Create PR for now to facilitate reviewing and discussion.
What it does:
- Before deserialize a profile, we try to update it first
- Did some hacking to ensure as little change as possible
- I added some **FIXME** marks on the things I'm sure if they are correct.
> CURA-3540 update profiles when deserializing them

- resources/i18n/ptbr/uranium.po
Brazilian portuguese strings updated
> updated brazilian portuguese strings for 2.6

- UM/Controller.py
- UM/Tool.py
- plugins/Tools/MirrorTool/MirrorTool.py
- plugins/Tools/RotateTool/RotateTool.py
- plugins/Tools/ScaleTool/ScaleTool.py
- plugins/Tools/TranslateTool/TranslateTool.py
As was requested on our forum, I made it possible for Tools to have a shortcut-key
CURA-3933
> Added shortcuts for MoveTool(Q) ScaleTool(A) RotateTool(Z)

- UM/Version.py
Fix firmware version decoding failed on modified releases tag.
CURA-3477
> Fix firmware version decoding failed on modified releases tag.

- UM/Event.py
- plugins/Tools/CameraTool/CameraTool.py
Based on the request https://github.com/Ultimaker/Cura/issues/1572
See also https://github.com/Ultimaker/Cura/pull/2037
> Added zoom to mouse functionality

- UM/Backend/Backend.py
- UM/Settings/ContainerRegistry.py
- UM/Settings/ContainerStack.py
- UM/Settings/DefinitionContainer.py
- UM/Settings/InstanceContainer.py
- UM/Settings/Interfaces.py
- UM/Settings/Models/SettingPropertyProvider.py
- UM/Settings/PropertyEvaluationContext.py
- UM/Settings/SettingFunction.py
- UM/Settings/Validator.py
- tests/Settings/ContainerTestPlugin/ContainerTestPlugin.py
- tests/Settings/TestContainerRegistry.py
- tests/Settings/TestContainerStack.py
- tests/Settings/TestSettingFunction.py
- tests/Settings/TestSettingInstance.py
- tests/Settings/TestValidator.py
> CURA-4186 Add stack context for function evaluation

- UM/Application.py
- UM/Preferences.py
- UM/Qt/Bindings/Theme.py
Required for this PR: https://github.com/Ultimaker/Cura/pull/2348
Contributes to issue CURA-4148.
> Allow application to set the default theme

- create_plugin.py
Cura 2.7 expects either a .curaplugin or a .umplugin file. This script is creating a .plugin file.
I assume we want a .umplugin file at least.
> create_plugin: create a .umplugin file at least

- create_plugin.py
An additional requirement since Cura 2.7.
> create_plugin: Don't forget about the plugin.json!

- UM/Settings/InstanceContainer.py
See https://github.com/Ultimaker/Cura/pull/2660.
> Cura 4447 update instance container

- UM/Qt/QtApplication.py
Useful if plugins depend on each other and it needs actions after they are all loaded.
> pluginsLoaded: Adding signal and emitting it after last checks

- UM/Qt/Bindings/MainWindow.py
- UM/Qt/Bindings/Theme.py
- UM/Qt/QtApplication.py
It's far from perfect, as it doesn't actually kill instances (windows keep on getting added, even though close is called).
I expect this is caused by some weird garbage collect issue. Could be that I'm missing something super obvious, so i'm still going to make the pull request.
> Reload qml

- plugins/UpdateChecker/UpdateCheckerJob.py
Just hit this line and thought about correcting it.
Might be that this is not conform to your coding conventions, but it looks better in my eyes.
> UpdateCheckerJob: Use multiple lines to make code better readable

- UM/FileHandler/ReadFileJob.py
We already have "Loading" in the message's title.
In my opinion one "Loading" too much..
> ReadFileJob: Removing "Loading" from message

- UM/Qt/QtApplication.py
.. it was a built-in function in Python 2.x. However, still feels like sand in my eyes..
> QtApplication: Prevent usage of "file"

- resources/i18n/pl_PL/uranium.po
Translated uranium.po file for Cura 3.1
> Cura 3.1 Uranium - Polish language

- UM/Controller.py
- UM/Qt/Bindings/Bindings.py
- UM/Qt/Bindings/ControllerProxy.py
- UM/Qt/Bindings/StageModel.py
- UM/Stage.py
See https://github.com/Ultimaker/Cura/pull/2928.
> Feature stages

- UM/Qt/QtApplication.py
It is a built-in function
(Managed to push into the wrong branch .. Same as #317)
> QtApplication: Prevent using dir

- UM/Application.py
- UM/Qt/Bindings/MainWindow.py
- UM/Qt/QtApplication.py
Needed to make Cura run as COM server.
_Features:_
* Hidden mode (no splash) ("Cura.exe --invisible")
* Adding possibility for plugins to add command line arguments
* Keep argument parser alive and throw an error on unknown arguments at the end of initialization
_Needed for:_
* Individual arguments in the InterfacePlugin (https://github.com/thopiekar/CuraInterfacePlugin)
> (DONE) Registration of arguments of plugins, add invisible mode (No splashscreen!) and "--debug" mode as argument

- UM/PluginObject.py
- UM/PluginRegistry.py
- UM/Qt/Bindings/PluginsModel.py
- UM/Qt/qml/UM/Preferences/PluginsPage.qml
I've consolidated a lot of functionality within the plugin registry and as far as I can tell, everything is still working, but this is why I wanted to talk with Terri about being better able to know if something is going to fail tests.
> Plugin refactor

- UM/Qt/qml/UM/Preferences/MachinesPage.qml
- UM/Qt/qml/UM/Preferences/PluginsPage.qml
- plugins/Tools/ScaleTool/ScaleTool.qml
- plugins/Tools/TranslateTool/TranslateTool.qml
This is based on the 3.2 branch and also has a cura PR
CURA-4941
> Checked all divisions (again..) and multiplications on rounding errors

- UM/Qt/Bindings/Theme.py
Merging so Terri can build it.
> CURA-4790 Use "weight" instead of "bold" property

- UM/Qt/Bindings/Theme.py
Based on feedback from @fieldOfView.
> CURA-4790 If using "bold", use .setBold(), else use .setWeight()

- UM/Qt/Bindings/ActiveToolProxy.py
> Allow send triggerAction from Tool with parameters

- UM/Mesh/MeshBuilder.py
If a modification has been detected, a message will appear and ask for a reload.
I asked for this feature already months before, but decided to invest time on this on my own now.
Optionally: Adding a preference to turn on/off this feature
Note: This has been coded without testing inside Github's webpage.
> MeshBuilder: Watching files for modifications

- resources/i18n/zh_TW/uranium.po
Traditional Chinese translation for cura 3.3
> [3.3] Update zh_tw translation for cura 3.3

- tests/PluginRegistry/TestPluginRegistry.py
Commit 2ed8b3da7c changed from KeyError to PluginNotFoundError.
> Fix expected exception in test_emptyPlugin.

- UM/PackageManager.py
- UM/Settings/ContainerStack.py
- UM/Settings/InstanceContainer.py
- tests/Settings/TestRoundtripping.py
- tests/benchmarks/Settings/BenchmarkContainerRegistry.py
Added functions to make it able to explore package contents for above functionality in Cura.
> CURA-5389 Check and confirmation before Remove package 

- UM/PackageManager.py
Together with https://github.com/Ultimaker/Cura/pull/4150
> CURA-5541 Fix package manager inconsistent fields

- UM/FileHandler/FileWriter.py
- UM/FileHandler/WriteFileJob.py
- plugins/FileHandlers/OBJWriter/OBJWriter.py
- plugins/FileHandlers/STLWriter/STLWriter.py
That will give some more information to the user when a message is shown in the frontend.
> Add some extra information when the FileWriters can't write the files.

- UM/Scene/Selection.py
> CURA-5617 Use bounding box to compute group center instead of average

- UM/Math/Polygon.py
- UM/Math/ShapelyUtil.py
- UM/Scene/Iterator/Iterator.py
- UM/Scene/SceneNode.py
- UM/Scene/SceneNodeDecorator.py
Home made solution has bugs. For example, if it's processing two almost identical rectangles (e.g. with 0.0001 differences), then it can return an empty Polygon, indicating that there is no intersection.
Companion PR: https://github.com/Ultimaker/cura-build/pull/184
> CURA-5538 Fix intersection function

- UM/Qt/QtApplication.py
> Remove Fusion style so that system style is used

- UM/FileHandler/FileHandler.py
- UM/Qt/Bindings/OutputDeviceManagerProxy.py
- plugins/LocalFileOutputDevice/LocalFileOutputDevice.py
- New field "hide_in_file_dialog" for a file type.
- For a write file request, provide a complete list of preferred file
types and let it pick the best matching one.
> CURA-5649 Allow to hide file types in save file dialog

- resources/i18n/pt_BR/uranium.po
Updated strings to Cura/Uranium 3.5
> Updated strings to Uranium/Cura 3.5

- UM/Settings/ContainerQuery.py
- UM/Settings/ContainerRegistry.py
In case the application crashes at this point, we can have more information.
> Catch type errors when using matchType

- resources/i18n/de_DE/uranium.po
- resources/i18n/es_ES/uranium.po
- resources/i18n/fr_FR/uranium.po
- resources/i18n/it_IT/uranium.po
- resources/i18n/ja_JP/uranium.po
- resources/i18n/ko_KR/uranium.po
- resources/i18n/nl_NL/uranium.po
- resources/i18n/pt_PT/uranium.po
- resources/i18n/ru_RU/uranium.po
- resources/i18n/tr_TR/uranium.po
- resources/i18n/zh_CN/uranium.po
- resources/i18n/zh_TW/uranium.po
These are the updates for version 3.6 to the translations to every supported language except Polish and Brazilian.
Implements CURA-5870.
> Update translations for Uranium 3.6

- UM/VersionUpgradeManager.py
Allow the version upgrade to go more levels in depth to search for files to upgrade.
Contributes to CURA-5915.
> Search upgrade files in more levels deeper

- resources/bundled_packages/uranium.json
Apparently this is the new author_id.
Contributes to CURA-5926.
> Change the Ultimaker author_id to UltimakerPackages

- UM/Backend/Backend.py
- UM/MimeTypeDatabase.py
- UM/PluginRegistry.py
- UM/Qt/Bindings/BackendProxy.py
- UM/Settings/DefinitionContainer.py
- UM/Settings/SettingDefinition.py
- plugins/LocalContainerProvider/LocalContainerProvider.py
> Cura 6016 improve ui speed

- UM/Qt/Bindings/StageModel.py
> Simplify the stage model

- UM/Qt/ListModel.py
- Fixes a crash on Mac OS X
- Optimize the way `ListModel` updates data
> [4.0] CURA-6015 Optimize data update for ListModel

- UM/Settings/ContainerProvider.py
- UM/Settings/ContainerRegistry.py
- plugins/LocalContainerProvider/LocalContainerProvider.py
https://github.com/Ultimaker/Cura/pull/5022 needs this one
> [4.0] CURA-6035 Add getContainerFilePathById()

- UM/Settings/ContainerRegistry.py
This way the function can be overridden in subclasses.
Contributes to issue CURA-6270.
> Move check for valid metadata to separate function

- UM/Application.py
- UM/PackageManager.py
- UM/Qt/QtApplication.py
This adds a notification icon to the top of the marketplace if there are packages that have a newer version on the marketplace.
This is paired with https://github.com/Ultimaker/Cura/pull/5521
CURA-6151
> Notify updates in marketplace

- UM/Decorators.py
- UM/__init__.py
- plugins/ConsoleLogger/ConsoleLogger.py
- plugins/FileLogger/FileLogger.py
> Handle 'log once'.

- UM/Controller.py
- UM/Qt/Bindings/ControllerProxy.py
- UM/Qt/Bindings/MainWindow.py
- UM/Scene/Camera.py
- UM/Scene/Scene.py
- UM/Scene/ToolHandle.py
- plugins/Tools/CameraTool/CameraTool.py
- plugins/Tools/RotateTool/RotateTool.py
- plugins/Tools/ScaleTool/ScaleTool.py
This adds the much awaited orthographic view! 
It requires https://github.com/Ultimaker/Cura/pull/5768 to work 
CURA-5395
> Support for orthographic view

- UM/Settings/SettingDefinition.py
- UM/Settings/Validator.py
- tests/Settings/TestValidator.py
https://github.com/Ultimaker/Cura/pull/5863
> Don't prime-blob when print-sequence is one-at-a-time. [CURA-6414]

- UM/Settings/SettingDefinition.py
- UM/Settings/Validator.py
- tests/Settings/TestValidator.py
> Add a way to check is a setting is an UUID.

- UM/Controller.py
Fix regression introduced in https://github.com/Ultimaker/Uranium/commit/661bbfabb036c38ae53847203ef256380858da28.
> Fix snarf and barf regression!

- UM/Math/Polygon.py
I built Cura with master branch, but putting STL model to the plate throws this error:
"ValueError: Null geometry supports no operations", and crashes.
So I made workaround by surrounding problematic code with _is_empty.
Returns None if empty, continue if NOT empty.
Here is the log.
```
2019-07-28 19:20:03,001 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [56]: Loading shader file [/Users/kangdroid/Desktop/prog/3DPrinting/Cura/cura-build/build/build/Ultimaker Cura.app/Contents/MacOS/resources/shaders/transparent_object.shader]...
2019-07-28 19:20:03,081 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [61]: An uncaught error has occurred!
2019-07-28 19:20:03,084 - CRITICAL - [MainThread] cura.CrashHandler.__init__ [64]: Traceback (most recent call last):
2019-07-28 19:20:03,087 …
```
> Fix "ValueError: Null geometry supports no operations"

- UM/Math/Polygon.py
Should've check code more. Sorry for my mistake
@Ghostkeeper
> Fix: Empty check should be put before is_valid.

- plugins/UpdateChecker/UpdateCheckerJob.py
Use certifi CA file to do SSL/TLS verification.
> CURA-6698 Fix SSL verification

- UM/Scene/Selection.py
- UM/Scene/ToolHandle.py
- UM/View/GL/OpenGL.py
- UM/View/SelectionPass.py
- plugins/Tools/RotateTool/RotateTool.py
- plugins/Tools/RotateTool/RotateTool.qml
- plugins/Tools/SelectionTool/SelectionTool.py
- resources/shaders/select_face.shader
- resources/shaders/selection.shader
- tests/TestTools.py
Wraps up development for the 'lay flat by face' feature, at least concerning the 4.3-BETA (we'll probably revisit it in the near future).
(See also the PR in Cura, https://github.com/Ultimaker/Cura/pull/6328)
> CURA-6754 / CURA-6761 Fix Select Face

- UM/PackageManager.py
Some packages have LICENSE.txt or LICENSE.md in it. So get those files too.
Some packages also have packages in subfolders with different licenses. Sort the paths by length so we get the license file with the shortest path first (which will usually be in the main folder).
> Fix getting correct license file

- plugins/Tools/RotateTool/RotateTool.py
- resources/shaders/select_face.shader
See https://github.com/Ultimaker/Cura/issues/6387
> fix glsl lies

- resources/i18n/pt_BR/uranium.po
Updated brazilian portuguese strings for Cura 4.3.
> Updated pt_BR strings for Cura 4.3

- resources/i18n/de_DE/uranium.po
- resources/i18n/es_ES/uranium.po
- resources/i18n/fr_FR/uranium.po
- resources/i18n/it_IT/uranium.po
- resources/i18n/ja_JP/uranium.po
- resources/i18n/ko_KR/uranium.po
- resources/i18n/nl_NL/uranium.po
- resources/i18n/pt_PT/uranium.po
- resources/i18n/ru_RU/uranium.po
- resources/i18n/tr_TR/uranium.po
- resources/i18n/zh_CN/uranium.po
- resources/i18n/zh_TW/uranium.po
These are our new translations we got from Lionbridge for Uranium 4.3.
Contributes to issue CURA-6768.
> 4.3 translations lionbridge

- UM/Controller.py
Need to clear all tools on my scene and add my own "toolset". However, in this toolset there is no TranslateTool and I would like to fall back to a different tool.
Of course, it would be convenient to have also get* and set* functions, but I don't care about these right now.
> UM.Controller: Adding variable for tool fallback

- UM/Preferences.py
- UM/Qt/Bindings/ControllerProxy.py
- plugins/ConsoleLogger/plugin.json
- plugins/FileHandlers/OBJReader/plugin.json
- plugins/FileHandlers/OBJWriter/plugin.json
- plugins/FileHandlers/STLReader/plugin.json
- plugins/FileHandlers/STLWriter/plugin.json
- plugins/FileLogger/plugin.json
- plugins/LocalContainerProvider/plugin.json
- plugins/LocalFileOutputDevice/plugin.json
- plugins/Tools/CameraTool/plugin.json
- plugins/Tools/MirrorTool/plugin.json
- plugins/Tools/RotateTool/plugin.json
- plugins/Tools/ScaleTool/plugin.json
- plugins/Tools/SelectionTool/plugin.json
- plugins/Tools/TranslateTool/plugin.json
- plugins/UpdateChecker/plugin.json
- plugins/Views/SimpleView/plugin.json
- resources/bundled_packages/uranium.json
- tests/Settings/ContainerTestPlugin/plugin.json
- tests/conftest.py
> Change SDK version to 7.0.0

- UM/Settings/ContainerQuery.py
- UM/Settings/ContainerRegistry.py
- tests/Settings/TestContainerRegistry.py
These are performance improvements for Uranium applications w.r.t. the query system for the container registry.
* Cache intermediary results of queries.
* Increase cache size.
This belongs to this PR on Cura: https://github.com/Ultimaker/Cura/pull/6542
Implements CURA-6793.
> Performance improvements

- UM/Scene/Selection.py
- tests/Scene/TestSelection.py
Face selection tests.
Sorry for the spurious commits, also testing the signed/verified system :-D
> Selection Tests Update

- UM/Settings/Models/SettingPropertyProvider.py
- tests/Settings/TestSettingPropertyProvider.py
I dusted off the good 'ol qml profiler to make things a bit faster.
Linked with https://github.com/Ultimaker/Cura/pull/6583
> Switch the updates of the settingPropertyProvider to _updateDelayed

- UM/PackageManager.py
Goes with https://github.com/Ultimaker/Cura/pull/6615.
It would be great to have this in 4.4, but since we're in feature freeze I can understand why you'd want this on master instead.
> Packages API speed improvements

- UM/Application.py
- UM/LockFile.py
- UM/PluginRegistry.py
- UM/Settings/ContainerRegistry.py
- UM/Settings/InstanceContainer.py
- UM/Settings/Interfaces.py
- UM/Trust.py
- plugins/LocalContainerProvider/LocalContainerProvider.py
- scripts/createkeypair.py
- scripts/signfile.py
- scripts/signfolder.py
- tests/Settings/ContainerTestPlugin/ContainerTestPlugin.py
- tests/Settings/MockContainer.py
P/A reviewers/testers: You can test it with the scripts: './scripts/createkeypair.py', './scripts/signfolder.py' and './scripts/signfile.py'. Use the sign folder one to sign plugins and the sign file one to sign files. Put the public key next to the app.
(See also the relevant [Cura PR](https://github.com/Ultimaker/Cura/pull/6616), though it's way smaller.)
> CURA-6856 signed plugins and packages

- UM/Mesh/MeshData.py
Just to be able to determine the node points of a face.
Found the function inside the getFacePlane() function and extracted it for my needs.
> MeshData: Adding separate getFaceNodes() function

- UM/Trust.py
- tests/TestTrust.py
> Test signing and verification.

- UM/Qt/QtApplication.py
Added property `ApplicationDisplayName` to QtApplication
> Added property ApplicationDisplayName to QtApplication

- UM/PluginRegistry.py
- UM/Qt/QtApplication.py
- UM/VersionUpgradeManager.py
Add some intermediate loading messages and make sure the messages are shown at the right moment
> CURA-6823_improve_splash_screen_responsiveness

- run_mypy.py
Same change as for https://github.com/Ultimaker/Cura/pull/6884
> Ensure that mypy commands run side by side

- UM/PackageManager.py
- UM/PluginRegistry.py
Refactored the function to only show the packages names.
Part of https://github.com/Ultimaker/Cura/pull/6845.
> CURA-7038/Show list of packages to be synced

- UM/PackageManager.py
- UM/Qt/Bindings/ExtensionModel.py
- UM/Qt/qml/UM/MessageStack.qml
- UM/TaskManagement/HttpRequestManager.py
- UM/TaskManagement/HttpRequestScope.py
- tests/TestPackageManager.py
Adds the concept of Scope to the HttpRequestManager, which is like a request interceptor. Useful to add fixed headers to a set of requests, like user-agent and Authorization
See accompanying Cura PR
> Cura 6983 sync packages

- UM/Qt/QtApplication.py
- UM/View/GL/OpenGLContext.py
The most important thing for the fix itself is the 'keep in memory' thing, but we might want the other stuff just in case.
> CURA-6670 Fix windows/opengl/intel-drivers hang

- UM/Qt/qml/UM/Dialog.qml
> Add backgroundColor as a property for Dialog.qml

- UM/PackageManager.py
Has a companion Cura PR 
CURA-7099
> Emit a signal when a package is installed

- resources/i18n/de_DE/uranium.po
- resources/i18n/es_ES/uranium.po
- resources/i18n/fr_FR/uranium.po
- resources/i18n/it_IT/uranium.po
- resources/i18n/ja_JP/uranium.po
- resources/i18n/ko_KR/uranium.po
- resources/i18n/nl_NL/uranium.po
- resources/i18n/pt_PT/uranium.po
- resources/i18n/ru_RU/uranium.po
- resources/i18n/tr_TR/uranium.po
- resources/i18n/zh_CN/uranium.po
Contributes to issue CURA-7201.
> Update translations from Lionbridge for 4.5

- UM/PluginRegistry.py
- UM/Trust.py
Before, Cura would crash when encountering an untrusted plugin
> Show error when an enterprise plugin could not be verified.

- UM/Trust.py
It will get automatically packed into builds when in the Resources
CURA-7016
> Move the package signature pem file to the Resources folder

- UM/Message.py
- UM/Qt/Bindings/VisibleMessagesModel.py
- UM/TaskManagement/HttpRequestManager.py
- UM/TaskManagement/HttpRequestScope.py
Some uttility methods addedd to HttpRequestManager. See CURA-7150 for usages
> CURA-7150_proper_http_request_headers

- UM/TaskManagement/HttpRequestManager.py
- UM/TaskManagement/HttpRequestScope.py
Note created on top of Cura-7150
> Cura 7173 validate uploads

- UM/TaskManagement/HttpRequestManager.py
> Fix crash when losing internet connection while Cura is running

- plugins/ConsoleLogger/plugin.json
- plugins/FileHandlers/OBJReader/plugin.json
- plugins/FileHandlers/OBJWriter/plugin.json
- plugins/FileHandlers/STLReader/plugin.json
- plugins/FileHandlers/STLWriter/plugin.json
- plugins/FileLogger/plugin.json
- plugins/LocalContainerProvider/plugin.json
- plugins/LocalFileOutputDevice/plugin.json
- plugins/Tools/CameraTool/plugin.json
- plugins/Tools/MirrorTool/plugin.json
- plugins/Tools/RotateTool/plugin.json
- plugins/Tools/ScaleTool/plugin.json
- plugins/Tools/SelectionTool/plugin.json
- plugins/Tools/TranslateTool/plugin.json
- plugins/UpdateChecker/plugin.json
- plugins/Views/SimpleView/plugin.json
- tests/conftest.py
Not sure this is necessary since this is just a test, but it seems to be kept up to date, so here you go
> CURA-7383_sdk_ver_7_2_0

- UM/PackageManager.py
- tests/TestPackageManager.py
Cherry-pick the commits that fix the persistent bundled packages notification.
Merge along with https://github.com/Ultimaker/Cura/pull/7824
CURA-7459
CURA-7245
> Cherry-pick changes from CURA-7245_fix_bundled_package_sync

- UM/TaskManagement/HttpRequestManager.py
Also fix a spammy internal Qt error because we called error() too many
times.
CURA-7437
> Reset Qt Network manager on unknown network error

- UM/Qt/qml/UM/MessageStack.qml
This way we can display lists and links in the message.
Merge along with https://github.com/Ultimaker/Cura/pull/7873
CURA-7438
> Convert MessageStack text into RichText

- UM/Settings/InstanceContainer.py
- tests/Settings/TestInstanceContainer.py
On my machine this knocks it from 2.5 seconds to 1.5 seconds.
> Speed up the loading of metadata from instance containers

- UM/Application.py
- UM/Settings/Interfaces.py
- UM/Settings/Models/SettingDefinitionsModel.py
Requries https://github.com/Ultimaker/Uranium/pull/617 to be merged first.
Merge along with https://github.com/Ultimaker/Cura/pull/7904.
> Cura 7454 add remove printers button in removed printers from account message

- UM/TaskManagement/HttpRequestManager.py
and using ConnectionStatus as proxy for it.
CURA-7492
> Re-implement ConnectionStatus by adding a pyqtSignal to HttpRequestMgr

- UM/Qt/QtRenderer.py
- UM/Scene/SceneNode.py
- UM/View/DefaultPass.py
- UM/View/GL/ShaderProgram.py
- UM/View/RenderBatch.py
- UM/View/Renderer.py
- UM/View/SelectionPass.py
CURA-7106
needs https://github.com/Ultimaker/Cura/pull/7971
> CURA-7106 speedup multiple objects on build plate

- UM/Settings/SettingDefinition.py
CURA-7122
https://github.com/Ultimaker/Cura/pull/7993
> Cura 7122 include description in search field

- UM/Settings/Models/SettingDefinitionsModel.py
Fixes https://github.com/Ultimaker/Cura/issues/7967
> CURA-7540 wrong setting visibility after project import

- plugins/ConsoleLogger/plugin.json
- plugins/FileHandlers/OBJReader/plugin.json
- plugins/FileHandlers/OBJWriter/plugin.json
- plugins/FileHandlers/STLReader/plugin.json
- plugins/FileHandlers/STLWriter/plugin.json
- plugins/FileLogger/plugin.json
- plugins/LocalContainerProvider/plugin.json
- plugins/LocalFileOutputDevice/plugin.json
- plugins/Tools/CameraTool/plugin.json
- plugins/Tools/MirrorTool/plugin.json
- plugins/Tools/RotateTool/plugin.json
- plugins/Tools/ScaleTool/plugin.json
- plugins/Tools/SelectionTool/plugin.json
- plugins/Tools/TranslateTool/plugin.json
- plugins/UpdateChecker/plugin.json
- plugins/Views/SimpleView/plugin.json
- resources/bundled_packages/uranium.json
- tests/conftest.py
In preparation for 4.7 release.
CURA-7641
> CURA-7641: Update SDK version to 7.3.0

- plugins/FileHandlers/OBJReader/OBJReader.py
Should fix #635
Not tested yet, so this is a draft. Feel free to consider it non-draft if another dev has tested it.
> OBJ files can have negative indices.

- UM/Operations/RotateOperation.py
CURA-7440
Also needs:
https://github.com/Ultimaker/Cura/pull/8503
> Swap out arrange for PyNest2d

- plugins/Tools/ScaleTool/ScaleTool.py
- plugins/Tools/ScaleTool/tests/TestScaleTool.py
We all know what this issue is about. 
Turns out someone flat out disabled a previous fix that we had for this...
Should fix https://github.com/Ultimaker/Cura/issues/4136
CURA-5611
> Other axes % scale when rescaling non uniform after rotate

- UM/Scene/Scene.py
Fixes file watcher on windows when loading a file from a removable device (USB/SD-Card/...). Crash happens because QEventLoop is expected to be active before adding a path to the file watcher and the removable device seems to not have one ready. Manually create QEventLoop to fix this issue (QEventLoop gets created anyways in a later stage).
Benefit: File watcher can be used again on windows for reloading files automatically on change.
> Fix file watcher on windows for removable devices

- UM/Math/Polygon.py
In some cases, the 8 segments option is far too rough.
CURA-7643
> Make approximate circle accept how many segments it should use

- plugins/ConsoleLogger/plugin.json
- plugins/FileHandlers/OBJReader/plugin.json
- plugins/FileHandlers/OBJWriter/plugin.json
- plugins/FileHandlers/STLReader/plugin.json
- plugins/FileHandlers/STLWriter/plugin.json
- plugins/FileLogger/plugin.json
- plugins/LocalContainerProvider/plugin.json
- plugins/LocalFileOutputDevice/plugin.json
- plugins/Tools/CameraTool/plugin.json
- plugins/Tools/MirrorTool/plugin.json
- plugins/Tools/RotateTool/plugin.json
- plugins/Tools/ScaleTool/plugin.json
- plugins/Tools/SelectionTool/plugin.json
- plugins/Tools/TranslateTool/plugin.json
- plugins/UpdateChecker/plugin.json
- plugins/Views/SimpleView/plugin.json
- resources/bundled_packages/uranium.json
- tests/conftest.py
In preparation for the 4.8 release
CURA-7795
> Up the SDK version to 7.4.0

- resources/i18n/de_DE/uranium.po
- resources/i18n/es_ES/uranium.po
- resources/i18n/fr_FR/uranium.po
- resources/i18n/it_IT/uranium.po
- resources/i18n/ja_JP/uranium.po
- resources/i18n/ko_KR/uranium.po
- resources/i18n/nl_NL/uranium.po
- resources/i18n/pt_PT/uranium.po
- resources/i18n/ru_RU/uranium.po
- resources/i18n/tr_TR/uranium.po
- resources/i18n/zh_CN/uranium.po
- resources/i18n/zh_TW/uranium.po
> CURA-7782 Add Taiwanese translations for 4.8

- UM/Application.py
- UM/FileProvider.py
- UM/Qt/Bindings/Bindings.py
- UM/Qt/Bindings/FileProviderModel.py
- UM/Qt/QtApplication.py
> CURA-7868: Introduce the file provider plugin type

- UM/Application.py
- UM/FileHandler/FileHandler.py
- UM/FileHandler/ReadFileJob.py
- UM/FileProvider.py
- UM/Logger.py
- UM/Mesh/MeshFileHandler.py
- UM/Mesh/ReadMeshJob.py
- UM/Qt/Bindings/Bindings.py
- UM/Qt/Bindings/FileProviderModel.py
- UM/Qt/QtApplication.py
- UM/Workspace/WorkspaceFileHandler.py
Digital Factory!
Internal ticket: CURA-7864
See also:
https://github.com/Ultimaker/Cura/pull/9089
https://github.com/Ultimaker/cura-private-data/pull/68
> Open remote files MVP

- UM/PluginRegistry.py
- UM/Trust.py
- scripts/createkeypair.py
- scripts/signfile.py
- scripts/signfolder.py
- tests/TestTrust.py
Signature files should be self-signed.
> [CURA-7737] Sign Manifest

- UM/OutputDevice/OutputDeviceManager.py
- UM/OutputDevice/ProjectOutputDevice.py
- UM/Qt/Bindings/Bindings.py
- UM/Qt/Bindings/ProjectOutputDevicesModel.py
- plugins/LocalFileOutputDevice/LocalFileOutputDevice.py
- plugins/LocalFileOutputDevice/LocalFileOutputDevicePlugin.py
> CURA-7865 Save file in existing project mvp

- UM/FileProvider.py
- UM/OutputDevice/OutputDeviceManager.py
- UM/Qt/Bindings/FileProviderModel.py
Which is done by adding a 'priority' field to FileProvider (at least what Uranium is concerned).
> [CURA-7995] Fix from/to remote menu order w.r.t. normal flow

- UM/Workspace/WorkspaceFileHandler.py
CURA-8034
https://github.com/Ultimaker/Cura/pull/9371
> Add enabled property to workspace file handler

- UM/Application.py
- UM/Qt/QtApplication.py
- UM/Workspace/WorkspaceMetadataStorage.py
- tests/TestWorkspaceMetadataStorage.py
> CURA-7903: Allow plugins to keep temp workspace information in Cura

- UM/Qt/QtApplication.py
Credits go to @smartavionics 
https://github.com/smartavionics/Uranium/commit/566c30bc14e330c82627b5351619d6c343945618
Contributes to issue CURA-7813.
> Fix crash on exit

- UM/Qt/qml/UM/ApplicationMenu.qml
- UM/Qt/qml/UM/Dialog.qml
- UM/Qt/qml/UM/MessageStack.qml
- UM/Qt/qml/UM/Preferences/ConfirmRemoveDialog.qml
- UM/Qt/qml/UM/Preferences/GeneralPage.qml
- UM/Qt/qml/UM/Preferences/MachinesPage.qml
- UM/Qt/qml/UM/Preferences/ManagementPage.qml
- UM/Qt/qml/UM/Preferences/PreferencesDialog.qml
- UM/Qt/qml/UM/Preferences/PreferencesPage.qml
- UM/Qt/qml/UM/Preferences/RenameDialog.qml
- UM/Qt/qml/UM/Preferences/SettingVisibilityCategory.qml
- UM/Qt/qml/UM/Preferences/SettingVisibilityItem.qml
- UM/Qt/qml/UM/ProgressBar.qml
- UM/Qt/qml/UM/RecolorImage.qml
- UM/Qt/qml/UM/SimpleButton.qml
- UM/Qt/qml/UM/TabRow.qml
- UM/Qt/qml/UM/TabRowButton.qml
- UM/Qt/qml/UM/TooltipArea.qml
- UM/Qt/qml/UM/Wizard.qml
- examples/definition_viewer/main.qml
- plugins/Tools/RotateTool/RotateTool.qml
- plugins/Tools/ScaleTool/ScaleTool.qml
- plugins/Tools/TranslateTool/TranslateTool.qml
> Update versions of Qt modules

- UM/Qt/qml/UM/ApplicationMenu.qml
- UM/Qt/qml/UM/Dialog.qml
- UM/Qt/qml/UM/MessageStack.qml
- UM/Qt/qml/UM/Preferences/ConfirmRemoveDialog.qml
- UM/Qt/qml/UM/Preferences/GeneralPage.qml
- UM/Qt/qml/UM/Preferences/MachinesPage.qml
- UM/Qt/qml/UM/Preferences/ManagementPage.qml
- UM/Qt/qml/UM/Preferences/PreferencesDialog.qml
- UM/Qt/qml/UM/Preferences/PreferencesPage.qml
- UM/Qt/qml/UM/Preferences/RenameDialog.qml
- UM/Qt/qml/UM/Preferences/SettingVisibilityCategory.qml
- UM/Qt/qml/UM/Preferences/SettingVisibilityItem.qml
- UM/Qt/qml/UM/ProgressBar.qml
- UM/Qt/qml/UM/RecolorImage.qml
- UM/Qt/qml/UM/SimpleButton.qml
- UM/Qt/qml/UM/TabRow.qml
- UM/Qt/qml/UM/TabRowButton.qml
- UM/Qt/qml/UM/TooltipArea.qml
- UM/Qt/qml/UM/Wizard.qml
- examples/definition_viewer/main.qml
- plugins/Tools/RotateTool/RotateTool.qml
- plugins/Tools/ScaleTool/ScaleTool.qml
- plugins/Tools/TranslateTool/TranslateTool.qml
> Revert "Update versions of Qt modules"

- UM/Settings/DefinitionContainer.py
This speeds up the validation part of our unit tests (for cura) by about 20-25%
CURA-7508
> Add option for _mergeDicts to work in place without a copy

- UM/Preferences.py
- UM/Settings/ContainerStack.py
> Cura 8110 upgrader

- resources/i18n/pt_BR/uranium.po
Added new labels and fixed some verb declinations
> Updated pt_BR translation

- plugins/Tools/TranslateTool/TranslateTool.qml
This should fix Ultimaker/Cura#9450
> When translate tool values are empty, force them to 0

- UM/Qt/qml/UM/MessageStack.qml
- UM/Qt/qml/UM/Preferences/SettingVisibilityCategory.qml
- UM/Qt/qml/UM/Preferences/SettingVisibilityItem.qml
- UM/Qt/qml/UM/Wizard.qml
- plugins/Tools/MirrorTool/__init__.py
- plugins/Tools/RotateTool/RotateTool.qml
- plugins/Tools/RotateTool/__init__.py
- plugins/Tools/ScaleTool/ScaleTool.qml
- plugins/Tools/ScaleTool/__init__.py
- plugins/Tools/TranslateTool/__init__.py
Because we simply don't have time to properly fix all of this for 4.10, we are reverting these changes for now. This revert will be reverted for the release after this. 
CURA-8267
https://github.com/Ultimaker/Cura/pull/9916
> Revert "Update Icons"

- UM/CentralFileStorage.py
- UM/PluginRegistry.py
- UM/Trust.py
> Fix central storage with signed plugins

- UM/Qt/Bindings/MainWindow.py
I'm not entirely sure if this will fix the second monitor crash, it might actually fix it. Even if it doesn't, it does make the code a bit cleaner.
> Check the window size before setting it

- UM/Message.py
- UM/PackageManager.py
- UM/PluginRegistry.py
Cura-8313
https://github.com/Ultimaker/Cura/pull/9991
> Show message when plugin could not be loaded

- UM/Qt/qml/UM/MessageStack.qml
- UM/Qt/qml/UM/Preferences/SettingVisibilityCategory.qml
- UM/Qt/qml/UM/Preferences/SettingVisibilityItem.qml
- UM/Qt/qml/UM/Wizard.qml
- plugins/Tools/MirrorTool/__init__.py
- plugins/Tools/RotateTool/RotateTool.qml
- plugins/Tools/RotateTool/__init__.py
- plugins/Tools/ScaleTool/ScaleTool.qml
- plugins/Tools/ScaleTool/__init__.py
- plugins/Tools/TranslateTool/__init__.py
This re-introduces a new icon set, which was originally introduced for Uranium 4.10, but got reverted because it wasn't completely ready.
For discussions, please see https://github.com/Ultimaker/Cura/pull/10046.
Contributes to issue CURA-8342.
> Unrevert new icon set

- UM/ConfigurationErrorMessage.py
- UM/FileHandler/ReadFileJob.py
- UM/Mesh/ReadMeshJob.py
- UM/PackageManager.py
- UM/PluginRegistry.py
- UM/Qt/Bindings/OutputDeviceManagerProxy.py
- UM/VersionUpgradeManager.py
- plugins/LocalFileOutputDevice/LocalFileOutputDevice.py
- plugins/Tools/RotateTool/RotateTool.py
- plugins/UpdateChecker/UpdateCheckerJob.py
- tests/TestMessage.py
CURA-8418
https://github.com/Ultimaker/Cura/pull/10198
> Update messages to use the message_types

- UM/Qt/qml/UM/MessageStack.qml
- UM/Qt/qml/UM/StatusIcon.qml
- UM/Qt/qml/UM/qmldir
Required by: https://github.com/Ultimaker/Cura/pull/10202
CURA-8439
> CURA-8439: Add the StatusIcon.qml and use it in the messages

- resources/i18n/cs_CZ/uranium.po
- resources/i18n/de_DE/uranium.po
- resources/i18n/es_ES/uranium.po
- resources/i18n/fi_FI/uranium.po
- resources/i18n/fr_FR/uranium.po
- resources/i18n/hu_HU/uranium.po
- resources/i18n/it_IT/uranium.po
- resources/i18n/ja_JP/uranium.po
- resources/i18n/ko_KR/uranium.po
- resources/i18n/nl_NL/uranium.po
- resources/i18n/pl_PL/uranium.po
- resources/i18n/pt_BR/uranium.po
- resources/i18n/pt_PT/uranium.po
- resources/i18n/ru_RU/uranium.po
- resources/i18n/tr_TR/uranium.po
- resources/i18n/uranium.pot
- resources/i18n/zh_CN/uranium.po
- resources/i18n/zh_TW/uranium.po
Cura PR: https://github.com/Ultimaker/Cura/pull/10266
CURA-8472
> CURA-8472: Prepare for the 4.11 translations

- resources/i18n/zh_TW/uranium.po
> Traditional Chinese

- resources/i18n/cs_CZ/uranium.po
- resources/i18n/de_DE/uranium.po
- resources/i18n/es_ES/uranium.po
- resources/i18n/fi_FI/uranium.po
- resources/i18n/fr_FR/uranium.po
- resources/i18n/hu_HU/uranium.po
- resources/i18n/it_IT/uranium.po
- resources/i18n/ja_JP/uranium.po
- resources/i18n/ko_KR/uranium.po
- resources/i18n/nl_NL/uranium.po
- resources/i18n/pl_PL/uranium.po
- resources/i18n/pt_BR/uranium.po
- resources/i18n/pt_PT/uranium.po
- resources/i18n/ru_RU/uranium.po
- resources/i18n/tr_TR/uranium.po
- resources/i18n/uranium.pot
- resources/i18n/zh_CN/uranium.po
- resources/i18n/zh_TW/uranium.po
These are the translations we've received from the Lionbridge translation service for Uranium 4.11.
Contributes to issue CURA-8472.
> Update 4.11 translations from Lionbridge

- UM/Operations/ScaleOperation.py
- plugins/Tools/ScaleTool/ScaleTool.py
> Fix the scaling of very large and small models

- UM/PackageManager.py
Merge along with https://github.com/Ultimaker/Cura/pull/10570.
CURA-8254
> CURA-8254: Trigger material profile sync with printer

- UM/Mesh/MeshData.py
- UM/Qt/QtRenderer.py
- UM/View/GL/ShaderProgram.py
- UM/View/RenderBatch.py
This reverts a change made to the rendering system in https://github.com/Ultimaker/Uranium/pull/721 .
See https://github.com/Ultimaker/Cura/pull/11036 for more information.
The revert made in this PR is a clean revert. No additional modifications were made and no merge conflicts were encountered.
Contributes to issue CURA-8736.
> Revert graphics buffer update

- UM/PackageManager.py
- UM/PluginRegistry.py
- UM/Qt/ListModel.py
See also the Cura PR Ultimaker/Cura#11027
> Cura 8587 disable update install and uninstall

- UM/Logger.py
- tests/TestUrlUtil.py
Although this doesn't solve the issue, it does allow us to actually get data on what is going wrong!
https://github.com/Ultimaker/Cura/pull/11193
CURA-8760
> Store log lines if no logger was added

- UM/Qt/qml/UM/ApplicationMenu.qml
- UM/Qt/qml/UM/CheckBox.qml
- UM/Qt/qml/UM/Menu.qml
- UM/Qt/qml/UM/MenuItem.qml
- UM/Qt/qml/UM/qmldir
CURA-8683 
https://github.com/Ultimaker/Cura/pull/11236
> Replace controls windows and menus

- UM/Math/Matrix.py
- UM/View/GL/ShaderProgram.py
Some small stuff that I found when looking at the profile file provided in https://github.com/Ultimaker/Cura/issues/11003
Note that these changes don't solve the real problem.
> Minor shader speedups

- UM/Qt/qml/UM/Dialog.qml
> [CURA-8956] Properly align buttons in Dialog

- UM/Qt/qml/UM/Preferences/ManagementPage.qml
- UM/Qt/qml/UM/Preferences/PreferencesDialog.qml
- UM/Qt/qml/UM/Preferences/PreferencesPage.qml
- UM/Qt/qml/UM/SimpleButton.qml
https://github.com/Ultimaker/Cura/pull/11506
CURA-8949
> Styling of preferences screens

- UM/Backend/Backend.py
CURA-8957
Fixes Ultimaker/Cura#11466
> Set default priority of backend to normal on Windows

- UM/Qt/qml/UM/Menu.qml
- UM/Qt/qml/UM/MenuItem.qml
CURA-8928
https://github.com/Ultimaker/Cura/pull/11521
> Menu visual fixes

- UM/Backend/Backend.py
- UM/Backend/SignalSocket.py
- plugins/Tools/CameraTool/tests/TestCameraTool.py
- tests/TestBackend.py
This PR is part of:
- Ultimaker/libArcus#131
- Ultimaker/libSavitar#39
- Ultimaker/pynest2d#16
- Ultimaker/Cura#11571
> Cura 7924 sip cmake build

- UM/Qt/qml/UM/CheckBox.qml
CURA-8978
https://github.com/Ultimaker/Cura/pull/11540
> Fix checkbox style and functionality

- UM/Qt/qml/UM/CheckBox.qml
> Show correct checkbox state

- UM/Qt/qml/UM/CheckBox.qml
- UM/Qt/qml/UM/TextFieldWithUnit.qml
Update checkboxes, radio and textinput to align with new designs.
CURA-8991
> [CURA-8991] Align input component styling

- UM/Qt/qml/UM/Preferences/ManagementPage.qml
- UM/Qt/qml/UM/Preferences/PreferencesDialog.qml
Reduce width of profiles list and printers list.
Reduce width of buttons for selecting pages in preferences dialog
CURA-9008
https://github.com/Ultimaker/Cura/pull/11626
> [CURA-9008] Reduce width of preferences dialog page selection buttons.

- UM/Qt/qml/UM/Preferences/ManagementPage.qml
Update italics logic to work with active profile on profiles page.
Fix height binding loop error in Management page
https://github.com/Ultimaker/Cura/pull/11696
CURA-9044
> [CURA-9044] Update Profiles page to show active profile in italics

- UM/Job.py
- UM/Qt/Bindings/ControllerProxy.py
- UM/Scene/Scene.py
- UM/Settings/Models/SettingDefinitionsModel.py
- UM/Stage.py
- tests/TestStage.py
As we're prepping for the 5.0 release, it's time to get rid of deprecated functions!
CURA-7810
https://github.com/Ultimaker/Cura/pull/11706
> Remove deprecated functions

- plugins/ConsoleLogger/plugin.json
- plugins/FileHandlers/OBJReader/plugin.json
- plugins/FileHandlers/OBJWriter/plugin.json
- plugins/FileHandlers/STLReader/plugin.json
- plugins/FileHandlers/STLWriter/plugin.json
- plugins/FileLogger/plugin.json
- plugins/LocalContainerProvider/plugin.json
- plugins/LocalFileOutputDevice/plugin.json
- plugins/Tools/CameraTool/plugin.json
- plugins/Tools/MirrorTool/plugin.json
- plugins/Tools/RotateTool/plugin.json
- plugins/Tools/ScaleTool/plugin.json
- plugins/Tools/SelectionTool/plugin.json
- plugins/Tools/TranslateTool/plugin.json
- plugins/UpdateChecker/plugin.json
- plugins/Views/SimpleView/plugin.json
- resources/bundled_packages/uranium.json
- tests/Settings/ContainerTestPlugin/plugin.json
- tests/conftest.py
See also Frontend: https://github.com/Ultimaker/Cura/pull/11824
> Upgrade SDK version to 8.0.0

- UM/Application.py
- UM/Resources.py
This fix will stop enterprise versions from searching user config folder for non storage type resources.
Refer to SEC-253 for more information
SEC-253
> [SEC-253] [CURA-8964] resource preference injection

- UM/Application.py
- UM/Resources.py
This fix will stop enterprise versions from searching user config folder for non storage type resources.
Refer to SEC-253 for more information
SEC-253
> [SEC-253] [CURA-8964] resource preference injection 5.0.0

- docs/translations.md
Add small note about a pitfall I ran into.
Update some outdated information about how mo files are generated.
> [CURA-1941] Update translation guide

- UM/Qt/qml/UM/Preferences/PreferencesDialog.qml
It wasn't using the themed background.
https://github.com/Ultimaker/Cura/pull/12634
CURA-9402
> Fix the background for darktheme for preference dialog

- docs/overview.md
- Improve clarity.
- Grammatical corrections.
- Improve layout so that each of the three classes described has its own paragraph and each paragraph starts with the name of the class.
> Improve Backend Documentation

- UM/Qt/QtApplication.py
> Dont show toast message for every time a message is spawned

- UM/Settings/InstanceContainer.py
CURA-9224
https://github.com/Ultimaker/Cura/pull/13209
> Add class function that merges two instance containers into one

- UM/Backend/Backend.py
See https://github.com/Ultimaker/Cura/pull/13360
CURA-9678
> [CURA-9678] Duplicate print jobs sent to cloud

- README.md
- docs/Building.md
- docs/Developing.md
- docs/Packaging.md
- docs/System Requirements.md
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-4b781e?style=for-the-badge&logoColor=white&logo=GitHub&labelColor=609926
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-9e122a?style=for-the-badge&logoColor=white&logo=GitLFS&labelColor=D81939
[Badge GitHub]: https://img.shields.io/badge/ＧｉｔＨｕｂ_Ｎｅｗｃｏｍｅｒｓ-be2e47?style=for-the-badge&logoColor=white&logo=BitWarden&labelColor=FD3A5C
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-8c3b63?style=for-the-badge&logoColor=white&logo=RuboCop&labelColor=c84f8c
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-4e2760?style=for-the-badge&logoColor=white&logo=AskUbuntu&labelColor=73398D
[Badge Info]: https://img.shields.io/badge/Ｉｎｆｏｒｍａｔｉｏｎ-01434e?style=for-the-badge&logoColor=white&logo=InternetArchive&labelColor …
> README Formatting

- UM/Settings/SettingDefinition.py
Settings that where enums could not properly be added by the additional settings mechanism for plugins. This fixes that.
> [CURA-10722] (redux) make 'additional' settings work for enums

- UM/Settings/ContainerStack.py
- resources/i18n/cs_CZ/uranium.po
- resources/i18n/de_DE/uranium.po
- resources/i18n/es_ES/uranium.po
- resources/i18n/fi_FI/uranium.po
- resources/i18n/fr_FR/uranium.po
- resources/i18n/hu_HU/uranium.po
- resources/i18n/it_IT/uranium.po
- resources/i18n/ja_JP/uranium.po
- resources/i18n/ko_KR/uranium.po
- resources/i18n/nl_NL/uranium.po
- resources/i18n/pl_PL/uranium.po
- resources/i18n/pt_BR/uranium.po
- resources/i18n/pt_PT/uranium.po
- resources/i18n/ru_RU/uranium.po
- resources/i18n/tr_TR/uranium.po
- resources/i18n/uranium.pot
- resources/i18n/zh_CN/uranium.po
- resources/i18n/zh_TW/uranium.po
This is a container stack bump, because we're not really updating a setting Instead, we are updating how the container stacks are built up. 
Goes together with https://github.com/Ultimaker/Cura/pull/16694
CURA-10953
> Bump version number of container stack

- UM/PluginRegistry.py
> Log error when plugin fails to register

- UM/Qt/Bindings/ActiveToolProxy.py
> Sentry: Error related to string to float conversion

- UM/Qt/qml/UM/Menu.qml
- UM/Qt/qml/UM/MenuItem.qml
Fix of the fix which (apparently) does not generate any more side-effects
CURA-11102
> [CURA-11102] qml warnings

- UM/PluginRegistry.py
done as part of Python 3.12 spike (CURA-11078)
> Replace deprecated imp module with importlib.

- resources/i18n/de_DE/uranium.po
Should fix https://github.com/Ultimaker/Cura/issues/17317
> Update Leben to Legen

- UM/TaskManagement/HttpRequestManager.py
> Fix OAuth token refresh after PC sleep

- UM/Qt/qml/UM/HelpIcon.qml
> adding warning to settings not in whitelist

- UM/View/GL/FrameBufferObject.py
> trying getting contents

- conandata.yml
> bump to 5.9.0-alpha.0

- resources/i18n/ja_JP/uranium.po
Tweaks common terms for Japanese translation.
- preference: プレファレンス -> 環境設定
**Test Configuration**:
* Operating System: Windows 11
> tweaks common terms for Japanese translation

- resources/i18n/ja_JP/uranium.po
Translated a new line for scaling tooltip.
**Test Configuration**:
* Operating System: Windows 11
> Updated ja translation for 5.10

- resources/i18n/de_DE/uranium.po
- resources/i18n/es_ES/uranium.po
- resources/i18n/fr_FR/uranium.po
- resources/i18n/it_IT/uranium.po
- resources/i18n/ja_JP/uranium.po
- resources/i18n/ko_KR/uranium.po
- resources/i18n/nl_NL/uranium.po
- resources/i18n/pt_PT/uranium.po
- resources/i18n/ru_RU/uranium.po
- resources/i18n/tr_TR/uranium.po
- resources/i18n/zh_CN/uranium.po
> Fix duplicate translation

- UM/Mesh/MeshBuilder.py
- UM/View/GL/Texture.py
Save and load painted models textures in 3MF files
:warning:  Based on CURA-12543, do not merge before other one is merged
CURA-12544
> CURA-12544 saving and loading painted files in cura

- UM/Math/Plane.py
- UM/Mesh/MeshData.py
- UM/Qt/qml/UM/Slider.qml
- UM/Scene/SceneNode.py
- UM/View/GL/OpenGL.py
- UM/View/GL/ShaderProgram.py
- UM/View/GL/Texture.py
- UM/View/SelectionPass.py
- Be able to update sub-images within the wrapper for OpenGL textures
- Add convenience method(s) such as for retrieving face-normals.
- Expose some things that previously weren't exposed, so we can render some very specific things we now need in the painting tool more efficiently -- the methods exposed don't require (much) knowledge of the internal workings, so it should be OK.
Frontend PR: https://github.com/Ultimaker/Cura/pull/20640
> [CURA-12543] Backend support of Painting UI

- UM/Math/Polygon.py
- UM/Mesh/MeshData.py
- UM/Scene/Camera.py
- UM/View/GL/Texture.py
- UM/View/SelectionPass.py
This PR adds a few methods that provide performances optimizations for the real-time painting.
It also changes the way the openGL object is updated, in order to reduce the total number of buffer copies.
CURA-12743
> CURA-12743 optimize painting performance
